package com.everwing.coreservice.wy.dao.mapper.other;

import com.everwing.coreservice.common.wy.entity.other.pojo.TcAgentCodeAndSysUser;
import com.everwing.coreservice.common.wy.entity.other.pojo.TcAgentCodeAndSysUserExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface TcAgentCodeAndSysUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tc_agent_code_and_sys_user
     *
     * @mbg.generated
     */
    long countByExample(TcAgentCodeAndSysUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tc_agent_code_and_sys_user
     *
     * @mbg.generated
     */
    int deleteByExample(TcAgentCodeAndSysUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tc_agent_code_and_sys_user
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tc_agent_code_and_sys_user
     *
     * @mbg.generated
     */
    int insert(TcAgentCodeAndSysUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tc_agent_code_and_sys_user
     *
     * @mbg.generated
     */
    int insertSelective(TcAgentCodeAndSysUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tc_agent_code_and_sys_user
     *
     * @mbg.generated
     */
    List<TcAgentCodeAndSysUser> selectByExample(TcAgentCodeAndSysUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tc_agent_code_and_sys_user
     *
     * @mbg.generated
     */
    TcAgentCodeAndSysUser selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tc_agent_code_and_sys_user
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TcAgentCodeAndSysUser record, @Param("example") TcAgentCodeAndSysUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tc_agent_code_and_sys_user
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TcAgentCodeAndSysUser record, @Param("example") TcAgentCodeAndSysUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tc_agent_code_and_sys_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TcAgentCodeAndSysUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tc_agent_code_and_sys_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TcAgentCodeAndSysUser record);
}