package com.everwing.coreservice.wy.dao.mapper.other;

import com.everwing.coreservice.common.wy.entity.other.pojo.TcAgentCode;
import com.everwing.coreservice.common.wy.entity.other.pojo.TcAgentCodeExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface TcAgentCodeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tc_agent_code
     *
     * @mbg.generated
     */
    long countByExample(TcAgentCodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tc_agent_code
     *
     * @mbg.generated
     */
    int deleteByExample(TcAgentCodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tc_agent_code
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String agentCodeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tc_agent_code
     *
     * @mbg.generated
     */
    int insert(TcAgentCode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tc_agent_code
     *
     * @mbg.generated
     */
    int insertSelective(TcAgentCode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tc_agent_code
     *
     * @mbg.generated
     */
    List<TcAgentCode> selectByExample(TcAgentCodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tc_agent_code
     *
     * @mbg.generated
     */
    TcAgentCode selectByPrimaryKey(String agentCodeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tc_agent_code
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TcAgentCode record, @Param("example") TcAgentCodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tc_agent_code
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TcAgentCode record, @Param("example") TcAgentCodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tc_agent_code
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TcAgentCode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tc_agent_code
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TcAgentCode record);
}