package com.everwing.coreservice.wy.dao.mapper.order;

import com.everwing.coreservice.common.wy.dto.MyWorkOrderDTO;
import com.everwing.coreservice.common.wy.entity.order.TcOrder;
import com.everwing.coreservice.common.wy.entity.order.TcOrderExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface TcOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tc_order
     *
     * @mbg.generated
     */
    long countByExample(TcOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tc_order
     *
     * @mbg.generated
     */
    int deleteByExample(TcOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tc_order
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String orderId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tc_order
     *
     * @mbg.generated
     */
    int insert(TcOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tc_order
     *
     * @mbg.generated
     */
    int insertSelective(TcOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tc_order
     *
     * @mbg.generated
     */
    List<TcOrder> selectByExampleWithBLOBs(TcOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tc_order
     *
     * @mbg.generated
     */
    List<TcOrder> selectByExample(TcOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tc_order
     *
     * @mbg.generated
     */
    TcOrder selectByPrimaryKey(String orderId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tc_order
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TcOrder record, @Param("example") TcOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tc_order
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("record") TcOrder record, @Param("example") TcOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tc_order
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TcOrder record, @Param("example") TcOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tc_order
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TcOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tc_order
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(TcOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tc_order
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TcOrder record);
    List<MyWorkOrderDTO> queryMyWorkOrder(@Param("accountId")String accountId, @Param("description")String description, @Param("date")String date, @Param("limit")int limit,@Param("pageSize")int pageSize) ;

    int updateProcessedWorkOrder(@Param("orderCode")String orderCode, @Param("status")String status, @Param("processDate")String processDate,@Param("procesInstructions")String procesInstructions,@Param("updateBy") String updateBy);
}