package com.everwing.coreservice.wy.dao.mapper.order;

import com.everwing.coreservice.common.wy.entity.order.TcOrderType;
import com.everwing.coreservice.common.wy.entity.order.TcOrderTypeExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface TcOrderTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tc_order_type
     *
     * @mbg.generated
     */
    long countByExample(TcOrderTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tc_order_type
     *
     * @mbg.generated
     */
    int deleteByExample(TcOrderTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tc_order_type
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String tcOrderTypeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tc_order_type
     *
     * @mbg.generated
     */
    int insert(TcOrderType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tc_order_type
     *
     * @mbg.generated
     */
    int insertSelective(TcOrderType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tc_order_type
     *
     * @mbg.generated
     */
    List<TcOrderType> selectByExample(TcOrderTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tc_order_type
     *
     * @mbg.generated
     */
    TcOrderType selectByPrimaryKey(String tcOrderTypeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tc_order_type
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TcOrderType record, @Param("example") TcOrderTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tc_order_type
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TcOrderType record, @Param("example") TcOrderTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tc_order_type
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TcOrderType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tc_order_type
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TcOrderType record);
}