package com.everwing.coreservice.common.wy.entity.order;

import java.io.Serializable;
import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table tc_order_type
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class TcOrderType implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tc_order_type.tc_order_type_id
     *
     * @mbg.generated
     */
    private String tcOrderTypeId;

    /**
     * Database Column Remarks:
     *   显示名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tc_order_type.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     * Database Column Remarks:
     *   最多三级联动
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tc_order_type.level
     *
     * @mbg.generated
     */
    private Integer level;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tc_order_type.parent_id
     *
     * @mbg.generated
     */
    private String parentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tc_order_type.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tc_order_type
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tc_order_type.tc_order_type_id
     *
     * @return the value of tc_order_type.tc_order_type_id
     *
     * @mbg.generated
     */
    public String getTcOrderTypeId() {
        return tcOrderTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tc_order_type.tc_order_type_id
     *
     * @param tcOrderTypeId the value for tc_order_type.tc_order_type_id
     *
     * @mbg.generated
     */
    public void setTcOrderTypeId(String tcOrderTypeId) {
        this.tcOrderTypeId = tcOrderTypeId == null ? null : tcOrderTypeId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tc_order_type.name
     *
     * @return the value of tc_order_type.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tc_order_type.name
     *
     * @param name the value for tc_order_type.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tc_order_type.level
     *
     * @return the value of tc_order_type.level
     *
     * @mbg.generated
     */
    public Integer getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tc_order_type.level
     *
     * @param level the value for tc_order_type.level
     *
     * @mbg.generated
     */
    public void setLevel(Integer level) {
        this.level = level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tc_order_type.parent_id
     *
     * @return the value of tc_order_type.parent_id
     *
     * @mbg.generated
     */
    public String getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tc_order_type.parent_id
     *
     * @param parentId the value for tc_order_type.parent_id
     *
     * @mbg.generated
     */
    public void setParentId(String parentId) {
        this.parentId = parentId == null ? null : parentId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tc_order_type.create_time
     *
     * @return the value of tc_order_type.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tc_order_type.create_time
     *
     * @param createTime the value for tc_order_type.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tc_order_type
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", tcOrderTypeId=").append(tcOrderTypeId);
        sb.append(", name=").append(name);
        sb.append(", level=").append(level);
        sb.append(", parentId=").append(parentId);
        sb.append(", createTime=").append(createTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}