package com.everwing.coreservice.common.wy.entity.order;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class TcOrderExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tc_order
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tc_order
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tc_order
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tc_order
     *
     * @mbg.generated
     */
    protected int limitStart = -1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tc_order
     *
     * @mbg.generated
     */
    protected int limitEnd = -1;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tc_order
     *
     * @mbg.generated
     */
    public TcOrderExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tc_order
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tc_order
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tc_order
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tc_order
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tc_order
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tc_order
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tc_order
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tc_order
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tc_order
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tc_order
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tc_order
     *
     * @mbg.generated
     */
    public void setLimitStart(int limitStart) {
        this.limitStart=limitStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tc_order
     *
     * @mbg.generated
     */
    public int getLimitStart() {
        return limitStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tc_order
     *
     * @mbg.generated
     */
    public void setLimitEnd(int limitEnd) {
        this.limitEnd=limitEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tc_order
     *
     * @mbg.generated
     */
    public int getLimitEnd() {
        return limitEnd;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tc_order
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andOrderIdIsNull() {
            addCriterion("order_id is null");
            return (Criteria) this;
        }

        public Criteria andOrderIdIsNotNull() {
            addCriterion("order_id is not null");
            return (Criteria) this;
        }

        public Criteria andOrderIdEqualTo(String value) {
            addCriterion("order_id =", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdNotEqualTo(String value) {
            addCriterion("order_id <>", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdGreaterThan(String value) {
            addCriterion("order_id >", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdGreaterThanOrEqualTo(String value) {
            addCriterion("order_id >=", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdLessThan(String value) {
            addCriterion("order_id <", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdLessThanOrEqualTo(String value) {
            addCriterion("order_id <=", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdLike(String value) {
            addCriterion("order_id like", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdNotLike(String value) {
            addCriterion("order_id not like", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdIn(List<String> values) {
            addCriterion("order_id in", values, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdNotIn(List<String> values) {
            addCriterion("order_id not in", values, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdBetween(String value1, String value2) {
            addCriterion("order_id between", value1, value2, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdNotBetween(String value1, String value2) {
            addCriterion("order_id not between", value1, value2, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderCodeIsNull() {
            addCriterion("order_code is null");
            return (Criteria) this;
        }

        public Criteria andOrderCodeIsNotNull() {
            addCriterion("order_code is not null");
            return (Criteria) this;
        }

        public Criteria andOrderCodeEqualTo(String value) {
            addCriterion("order_code =", value, "orderCode");
            return (Criteria) this;
        }

        public Criteria andOrderCodeNotEqualTo(String value) {
            addCriterion("order_code <>", value, "orderCode");
            return (Criteria) this;
        }

        public Criteria andOrderCodeGreaterThan(String value) {
            addCriterion("order_code >", value, "orderCode");
            return (Criteria) this;
        }

        public Criteria andOrderCodeGreaterThanOrEqualTo(String value) {
            addCriterion("order_code >=", value, "orderCode");
            return (Criteria) this;
        }

        public Criteria andOrderCodeLessThan(String value) {
            addCriterion("order_code <", value, "orderCode");
            return (Criteria) this;
        }

        public Criteria andOrderCodeLessThanOrEqualTo(String value) {
            addCriterion("order_code <=", value, "orderCode");
            return (Criteria) this;
        }

        public Criteria andOrderCodeLike(String value) {
            addCriterion("order_code like", value, "orderCode");
            return (Criteria) this;
        }

        public Criteria andOrderCodeNotLike(String value) {
            addCriterion("order_code not like", value, "orderCode");
            return (Criteria) this;
        }

        public Criteria andOrderCodeIn(List<String> values) {
            addCriterion("order_code in", values, "orderCode");
            return (Criteria) this;
        }

        public Criteria andOrderCodeNotIn(List<String> values) {
            addCriterion("order_code not in", values, "orderCode");
            return (Criteria) this;
        }

        public Criteria andOrderCodeBetween(String value1, String value2) {
            addCriterion("order_code between", value1, value2, "orderCode");
            return (Criteria) this;
        }

        public Criteria andOrderCodeNotBetween(String value1, String value2) {
            addCriterion("order_code not between", value1, value2, "orderCode");
            return (Criteria) this;
        }

        public Criteria andCustIdIsNull() {
            addCriterion("cust_id is null");
            return (Criteria) this;
        }

        public Criteria andCustIdIsNotNull() {
            addCriterion("cust_id is not null");
            return (Criteria) this;
        }

        public Criteria andCustIdEqualTo(String value) {
            addCriterion("cust_id =", value, "custId");
            return (Criteria) this;
        }

        public Criteria andCustIdNotEqualTo(String value) {
            addCriterion("cust_id <>", value, "custId");
            return (Criteria) this;
        }

        public Criteria andCustIdGreaterThan(String value) {
            addCriterion("cust_id >", value, "custId");
            return (Criteria) this;
        }

        public Criteria andCustIdGreaterThanOrEqualTo(String value) {
            addCriterion("cust_id >=", value, "custId");
            return (Criteria) this;
        }

        public Criteria andCustIdLessThan(String value) {
            addCriterion("cust_id <", value, "custId");
            return (Criteria) this;
        }

        public Criteria andCustIdLessThanOrEqualTo(String value) {
            addCriterion("cust_id <=", value, "custId");
            return (Criteria) this;
        }

        public Criteria andCustIdLike(String value) {
            addCriterion("cust_id like", value, "custId");
            return (Criteria) this;
        }

        public Criteria andCustIdNotLike(String value) {
            addCriterion("cust_id not like", value, "custId");
            return (Criteria) this;
        }

        public Criteria andCustIdIn(List<String> values) {
            addCriterion("cust_id in", values, "custId");
            return (Criteria) this;
        }

        public Criteria andCustIdNotIn(List<String> values) {
            addCriterion("cust_id not in", values, "custId");
            return (Criteria) this;
        }

        public Criteria andCustIdBetween(String value1, String value2) {
            addCriterion("cust_id between", value1, value2, "custId");
            return (Criteria) this;
        }

        public Criteria andCustIdNotBetween(String value1, String value2) {
            addCriterion("cust_id not between", value1, value2, "custId");
            return (Criteria) this;
        }

        public Criteria andCustTypeIsNull() {
            addCriterion("cust_type is null");
            return (Criteria) this;
        }

        public Criteria andCustTypeIsNotNull() {
            addCriterion("cust_type is not null");
            return (Criteria) this;
        }

        public Criteria andCustTypeEqualTo(String value) {
            addCriterion("cust_type =", value, "custType");
            return (Criteria) this;
        }

        public Criteria andCustTypeNotEqualTo(String value) {
            addCriterion("cust_type <>", value, "custType");
            return (Criteria) this;
        }

        public Criteria andCustTypeGreaterThan(String value) {
            addCriterion("cust_type >", value, "custType");
            return (Criteria) this;
        }

        public Criteria andCustTypeGreaterThanOrEqualTo(String value) {
            addCriterion("cust_type >=", value, "custType");
            return (Criteria) this;
        }

        public Criteria andCustTypeLessThan(String value) {
            addCriterion("cust_type <", value, "custType");
            return (Criteria) this;
        }

        public Criteria andCustTypeLessThanOrEqualTo(String value) {
            addCriterion("cust_type <=", value, "custType");
            return (Criteria) this;
        }

        public Criteria andCustTypeLike(String value) {
            addCriterion("cust_type like", value, "custType");
            return (Criteria) this;
        }

        public Criteria andCustTypeNotLike(String value) {
            addCriterion("cust_type not like", value, "custType");
            return (Criteria) this;
        }

        public Criteria andCustTypeIn(List<String> values) {
            addCriterion("cust_type in", values, "custType");
            return (Criteria) this;
        }

        public Criteria andCustTypeNotIn(List<String> values) {
            addCriterion("cust_type not in", values, "custType");
            return (Criteria) this;
        }

        public Criteria andCustTypeBetween(String value1, String value2) {
            addCriterion("cust_type between", value1, value2, "custType");
            return (Criteria) this;
        }

        public Criteria andCustTypeNotBetween(String value1, String value2) {
            addCriterion("cust_type not between", value1, value2, "custType");
            return (Criteria) this;
        }

        public Criteria andBuildingCodeIsNull() {
            addCriterion("building_code is null");
            return (Criteria) this;
        }

        public Criteria andBuildingCodeIsNotNull() {
            addCriterion("building_code is not null");
            return (Criteria) this;
        }

        public Criteria andBuildingCodeEqualTo(String value) {
            addCriterion("building_code =", value, "buildingCode");
            return (Criteria) this;
        }

        public Criteria andBuildingCodeNotEqualTo(String value) {
            addCriterion("building_code <>", value, "buildingCode");
            return (Criteria) this;
        }

        public Criteria andBuildingCodeGreaterThan(String value) {
            addCriterion("building_code >", value, "buildingCode");
            return (Criteria) this;
        }

        public Criteria andBuildingCodeGreaterThanOrEqualTo(String value) {
            addCriterion("building_code >=", value, "buildingCode");
            return (Criteria) this;
        }

        public Criteria andBuildingCodeLessThan(String value) {
            addCriterion("building_code <", value, "buildingCode");
            return (Criteria) this;
        }

        public Criteria andBuildingCodeLessThanOrEqualTo(String value) {
            addCriterion("building_code <=", value, "buildingCode");
            return (Criteria) this;
        }

        public Criteria andBuildingCodeLike(String value) {
            addCriterion("building_code like", value, "buildingCode");
            return (Criteria) this;
        }

        public Criteria andBuildingCodeNotLike(String value) {
            addCriterion("building_code not like", value, "buildingCode");
            return (Criteria) this;
        }

        public Criteria andBuildingCodeIn(List<String> values) {
            addCriterion("building_code in", values, "buildingCode");
            return (Criteria) this;
        }

        public Criteria andBuildingCodeNotIn(List<String> values) {
            addCriterion("building_code not in", values, "buildingCode");
            return (Criteria) this;
        }

        public Criteria andBuildingCodeBetween(String value1, String value2) {
            addCriterion("building_code between", value1, value2, "buildingCode");
            return (Criteria) this;
        }

        public Criteria andBuildingCodeNotBetween(String value1, String value2) {
            addCriterion("building_code not between", value1, value2, "buildingCode");
            return (Criteria) this;
        }

        public Criteria andOrderTypeId1IsNull() {
            addCriterion("order_type_id_1 is null");
            return (Criteria) this;
        }

        public Criteria andOrderTypeId1IsNotNull() {
            addCriterion("order_type_id_1 is not null");
            return (Criteria) this;
        }

        public Criteria andOrderTypeId1EqualTo(String value) {
            addCriterion("order_type_id_1 =", value, "orderTypeId1");
            return (Criteria) this;
        }

        public Criteria andOrderTypeId1NotEqualTo(String value) {
            addCriterion("order_type_id_1 <>", value, "orderTypeId1");
            return (Criteria) this;
        }

        public Criteria andOrderTypeId1GreaterThan(String value) {
            addCriterion("order_type_id_1 >", value, "orderTypeId1");
            return (Criteria) this;
        }

        public Criteria andOrderTypeId1GreaterThanOrEqualTo(String value) {
            addCriterion("order_type_id_1 >=", value, "orderTypeId1");
            return (Criteria) this;
        }

        public Criteria andOrderTypeId1LessThan(String value) {
            addCriterion("order_type_id_1 <", value, "orderTypeId1");
            return (Criteria) this;
        }

        public Criteria andOrderTypeId1LessThanOrEqualTo(String value) {
            addCriterion("order_type_id_1 <=", value, "orderTypeId1");
            return (Criteria) this;
        }

        public Criteria andOrderTypeId1Like(String value) {
            addCriterion("order_type_id_1 like", value, "orderTypeId1");
            return (Criteria) this;
        }

        public Criteria andOrderTypeId1NotLike(String value) {
            addCriterion("order_type_id_1 not like", value, "orderTypeId1");
            return (Criteria) this;
        }

        public Criteria andOrderTypeId1In(List<String> values) {
            addCriterion("order_type_id_1 in", values, "orderTypeId1");
            return (Criteria) this;
        }

        public Criteria andOrderTypeId1NotIn(List<String> values) {
            addCriterion("order_type_id_1 not in", values, "orderTypeId1");
            return (Criteria) this;
        }

        public Criteria andOrderTypeId1Between(String value1, String value2) {
            addCriterion("order_type_id_1 between", value1, value2, "orderTypeId1");
            return (Criteria) this;
        }

        public Criteria andOrderTypeId1NotBetween(String value1, String value2) {
            addCriterion("order_type_id_1 not between", value1, value2, "orderTypeId1");
            return (Criteria) this;
        }

        public Criteria andOrderTypeId2IsNull() {
            addCriterion("order_type_id_2 is null");
            return (Criteria) this;
        }

        public Criteria andOrderTypeId2IsNotNull() {
            addCriterion("order_type_id_2 is not null");
            return (Criteria) this;
        }

        public Criteria andOrderTypeId2EqualTo(String value) {
            addCriterion("order_type_id_2 =", value, "orderTypeId2");
            return (Criteria) this;
        }

        public Criteria andOrderTypeId2NotEqualTo(String value) {
            addCriterion("order_type_id_2 <>", value, "orderTypeId2");
            return (Criteria) this;
        }

        public Criteria andOrderTypeId2GreaterThan(String value) {
            addCriterion("order_type_id_2 >", value, "orderTypeId2");
            return (Criteria) this;
        }

        public Criteria andOrderTypeId2GreaterThanOrEqualTo(String value) {
            addCriterion("order_type_id_2 >=", value, "orderTypeId2");
            return (Criteria) this;
        }

        public Criteria andOrderTypeId2LessThan(String value) {
            addCriterion("order_type_id_2 <", value, "orderTypeId2");
            return (Criteria) this;
        }

        public Criteria andOrderTypeId2LessThanOrEqualTo(String value) {
            addCriterion("order_type_id_2 <=", value, "orderTypeId2");
            return (Criteria) this;
        }

        public Criteria andOrderTypeId2Like(String value) {
            addCriterion("order_type_id_2 like", value, "orderTypeId2");
            return (Criteria) this;
        }

        public Criteria andOrderTypeId2NotLike(String value) {
            addCriterion("order_type_id_2 not like", value, "orderTypeId2");
            return (Criteria) this;
        }

        public Criteria andOrderTypeId2In(List<String> values) {
            addCriterion("order_type_id_2 in", values, "orderTypeId2");
            return (Criteria) this;
        }

        public Criteria andOrderTypeId2NotIn(List<String> values) {
            addCriterion("order_type_id_2 not in", values, "orderTypeId2");
            return (Criteria) this;
        }

        public Criteria andOrderTypeId2Between(String value1, String value2) {
            addCriterion("order_type_id_2 between", value1, value2, "orderTypeId2");
            return (Criteria) this;
        }

        public Criteria andOrderTypeId2NotBetween(String value1, String value2) {
            addCriterion("order_type_id_2 not between", value1, value2, "orderTypeId2");
            return (Criteria) this;
        }

        public Criteria andOrderTypeId3IsNull() {
            addCriterion("order_type_id_3 is null");
            return (Criteria) this;
        }

        public Criteria andOrderTypeId3IsNotNull() {
            addCriterion("order_type_id_3 is not null");
            return (Criteria) this;
        }

        public Criteria andOrderTypeId3EqualTo(String value) {
            addCriterion("order_type_id_3 =", value, "orderTypeId3");
            return (Criteria) this;
        }

        public Criteria andOrderTypeId3NotEqualTo(String value) {
            addCriterion("order_type_id_3 <>", value, "orderTypeId3");
            return (Criteria) this;
        }

        public Criteria andOrderTypeId3GreaterThan(String value) {
            addCriterion("order_type_id_3 >", value, "orderTypeId3");
            return (Criteria) this;
        }

        public Criteria andOrderTypeId3GreaterThanOrEqualTo(String value) {
            addCriterion("order_type_id_3 >=", value, "orderTypeId3");
            return (Criteria) this;
        }

        public Criteria andOrderTypeId3LessThan(String value) {
            addCriterion("order_type_id_3 <", value, "orderTypeId3");
            return (Criteria) this;
        }

        public Criteria andOrderTypeId3LessThanOrEqualTo(String value) {
            addCriterion("order_type_id_3 <=", value, "orderTypeId3");
            return (Criteria) this;
        }

        public Criteria andOrderTypeId3Like(String value) {
            addCriterion("order_type_id_3 like", value, "orderTypeId3");
            return (Criteria) this;
        }

        public Criteria andOrderTypeId3NotLike(String value) {
            addCriterion("order_type_id_3 not like", value, "orderTypeId3");
            return (Criteria) this;
        }

        public Criteria andOrderTypeId3In(List<String> values) {
            addCriterion("order_type_id_3 in", values, "orderTypeId3");
            return (Criteria) this;
        }

        public Criteria andOrderTypeId3NotIn(List<String> values) {
            addCriterion("order_type_id_3 not in", values, "orderTypeId3");
            return (Criteria) this;
        }

        public Criteria andOrderTypeId3Between(String value1, String value2) {
            addCriterion("order_type_id_3 between", value1, value2, "orderTypeId3");
            return (Criteria) this;
        }

        public Criteria andOrderTypeId3NotBetween(String value1, String value2) {
            addCriterion("order_type_id_3 not between", value1, value2, "orderTypeId3");
            return (Criteria) this;
        }

        public Criteria andDescriptionIsNull() {
            addCriterion("description is null");
            return (Criteria) this;
        }

        public Criteria andDescriptionIsNotNull() {
            addCriterion("description is not null");
            return (Criteria) this;
        }

        public Criteria andDescriptionEqualTo(String value) {
            addCriterion("description =", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotEqualTo(String value) {
            addCriterion("description <>", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionGreaterThan(String value) {
            addCriterion("description >", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionGreaterThanOrEqualTo(String value) {
            addCriterion("description >=", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLessThan(String value) {
            addCriterion("description <", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLessThanOrEqualTo(String value) {
            addCriterion("description <=", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLike(String value) {
            addCriterion("description like", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotLike(String value) {
            addCriterion("description not like", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionIn(List<String> values) {
            addCriterion("description in", values, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotIn(List<String> values) {
            addCriterion("description not in", values, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionBetween(String value1, String value2) {
            addCriterion("description between", value1, value2, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotBetween(String value1, String value2) {
            addCriterion("description not between", value1, value2, "description");
            return (Criteria) this;
        }

        public Criteria andIsUrgentIsNull() {
            addCriterion("is_urgent is null");
            return (Criteria) this;
        }

        public Criteria andIsUrgentIsNotNull() {
            addCriterion("is_urgent is not null");
            return (Criteria) this;
        }

        public Criteria andIsUrgentEqualTo(Boolean value) {
            addCriterion("is_urgent =", value, "isUrgent");
            return (Criteria) this;
        }

        public Criteria andIsUrgentNotEqualTo(Boolean value) {
            addCriterion("is_urgent <>", value, "isUrgent");
            return (Criteria) this;
        }

        public Criteria andIsUrgentGreaterThan(Boolean value) {
            addCriterion("is_urgent >", value, "isUrgent");
            return (Criteria) this;
        }

        public Criteria andIsUrgentGreaterThanOrEqualTo(Boolean value) {
            addCriterion("is_urgent >=", value, "isUrgent");
            return (Criteria) this;
        }

        public Criteria andIsUrgentLessThan(Boolean value) {
            addCriterion("is_urgent <", value, "isUrgent");
            return (Criteria) this;
        }

        public Criteria andIsUrgentLessThanOrEqualTo(Boolean value) {
            addCriterion("is_urgent <=", value, "isUrgent");
            return (Criteria) this;
        }

        public Criteria andIsUrgentIn(List<Boolean> values) {
            addCriterion("is_urgent in", values, "isUrgent");
            return (Criteria) this;
        }

        public Criteria andIsUrgentNotIn(List<Boolean> values) {
            addCriterion("is_urgent not in", values, "isUrgent");
            return (Criteria) this;
        }

        public Criteria andIsUrgentBetween(Boolean value1, Boolean value2) {
            addCriterion("is_urgent between", value1, value2, "isUrgent");
            return (Criteria) this;
        }

        public Criteria andIsUrgentNotBetween(Boolean value1, Boolean value2) {
            addCriterion("is_urgent not between", value1, value2, "isUrgent");
            return (Criteria) this;
        }

        public Criteria andPrincipalSysUserIdIsNull() {
            addCriterion("principal_sys_user_id is null");
            return (Criteria) this;
        }

        public Criteria andPrincipalSysUserIdIsNotNull() {
            addCriterion("principal_sys_user_id is not null");
            return (Criteria) this;
        }

        public Criteria andPrincipalSysUserIdEqualTo(String value) {
            addCriterion("principal_sys_user_id =", value, "principalSysUserId");
            return (Criteria) this;
        }

        public Criteria andPrincipalSysUserIdNotEqualTo(String value) {
            addCriterion("principal_sys_user_id <>", value, "principalSysUserId");
            return (Criteria) this;
        }

        public Criteria andPrincipalSysUserIdGreaterThan(String value) {
            addCriterion("principal_sys_user_id >", value, "principalSysUserId");
            return (Criteria) this;
        }

        public Criteria andPrincipalSysUserIdGreaterThanOrEqualTo(String value) {
            addCriterion("principal_sys_user_id >=", value, "principalSysUserId");
            return (Criteria) this;
        }

        public Criteria andPrincipalSysUserIdLessThan(String value) {
            addCriterion("principal_sys_user_id <", value, "principalSysUserId");
            return (Criteria) this;
        }

        public Criteria andPrincipalSysUserIdLessThanOrEqualTo(String value) {
            addCriterion("principal_sys_user_id <=", value, "principalSysUserId");
            return (Criteria) this;
        }

        public Criteria andPrincipalSysUserIdLike(String value) {
            addCriterion("principal_sys_user_id like", value, "principalSysUserId");
            return (Criteria) this;
        }

        public Criteria andPrincipalSysUserIdNotLike(String value) {
            addCriterion("principal_sys_user_id not like", value, "principalSysUserId");
            return (Criteria) this;
        }

        public Criteria andPrincipalSysUserIdIn(List<String> values) {
            addCriterion("principal_sys_user_id in", values, "principalSysUserId");
            return (Criteria) this;
        }

        public Criteria andPrincipalSysUserIdNotIn(List<String> values) {
            addCriterion("principal_sys_user_id not in", values, "principalSysUserId");
            return (Criteria) this;
        }

        public Criteria andPrincipalSysUserIdBetween(String value1, String value2) {
            addCriterion("principal_sys_user_id between", value1, value2, "principalSysUserId");
            return (Criteria) this;
        }

        public Criteria andPrincipalSysUserIdNotBetween(String value1, String value2) {
            addCriterion("principal_sys_user_id not between", value1, value2, "principalSysUserId");
            return (Criteria) this;
        }

        public Criteria andNeedCallbackIsNull() {
            addCriterion("need_callback is null");
            return (Criteria) this;
        }

        public Criteria andNeedCallbackIsNotNull() {
            addCriterion("need_callback is not null");
            return (Criteria) this;
        }

        public Criteria andNeedCallbackEqualTo(Boolean value) {
            addCriterion("need_callback =", value, "needCallback");
            return (Criteria) this;
        }

        public Criteria andNeedCallbackNotEqualTo(Boolean value) {
            addCriterion("need_callback <>", value, "needCallback");
            return (Criteria) this;
        }

        public Criteria andNeedCallbackGreaterThan(Boolean value) {
            addCriterion("need_callback >", value, "needCallback");
            return (Criteria) this;
        }

        public Criteria andNeedCallbackGreaterThanOrEqualTo(Boolean value) {
            addCriterion("need_callback >=", value, "needCallback");
            return (Criteria) this;
        }

        public Criteria andNeedCallbackLessThan(Boolean value) {
            addCriterion("need_callback <", value, "needCallback");
            return (Criteria) this;
        }

        public Criteria andNeedCallbackLessThanOrEqualTo(Boolean value) {
            addCriterion("need_callback <=", value, "needCallback");
            return (Criteria) this;
        }

        public Criteria andNeedCallbackIn(List<Boolean> values) {
            addCriterion("need_callback in", values, "needCallback");
            return (Criteria) this;
        }

        public Criteria andNeedCallbackNotIn(List<Boolean> values) {
            addCriterion("need_callback not in", values, "needCallback");
            return (Criteria) this;
        }

        public Criteria andNeedCallbackBetween(Boolean value1, Boolean value2) {
            addCriterion("need_callback between", value1, value2, "needCallback");
            return (Criteria) this;
        }

        public Criteria andNeedCallbackNotBetween(Boolean value1, Boolean value2) {
            addCriterion("need_callback not between", value1, value2, "needCallback");
            return (Criteria) this;
        }

        public Criteria andSourceTypeIsNull() {
            addCriterion("source_type is null");
            return (Criteria) this;
        }

        public Criteria andSourceTypeIsNotNull() {
            addCriterion("source_type is not null");
            return (Criteria) this;
        }

        public Criteria andSourceTypeEqualTo(Integer value) {
            addCriterion("source_type =", value, "sourceType");
            return (Criteria) this;
        }

        public Criteria andSourceTypeNotEqualTo(Integer value) {
            addCriterion("source_type <>", value, "sourceType");
            return (Criteria) this;
        }

        public Criteria andSourceTypeGreaterThan(Integer value) {
            addCriterion("source_type >", value, "sourceType");
            return (Criteria) this;
        }

        public Criteria andSourceTypeGreaterThanOrEqualTo(Integer value) {
            addCriterion("source_type >=", value, "sourceType");
            return (Criteria) this;
        }

        public Criteria andSourceTypeLessThan(Integer value) {
            addCriterion("source_type <", value, "sourceType");
            return (Criteria) this;
        }

        public Criteria andSourceTypeLessThanOrEqualTo(Integer value) {
            addCriterion("source_type <=", value, "sourceType");
            return (Criteria) this;
        }

        public Criteria andSourceTypeIn(List<Integer> values) {
            addCriterion("source_type in", values, "sourceType");
            return (Criteria) this;
        }

        public Criteria andSourceTypeNotIn(List<Integer> values) {
            addCriterion("source_type not in", values, "sourceType");
            return (Criteria) this;
        }

        public Criteria andSourceTypeBetween(Integer value1, Integer value2) {
            addCriterion("source_type between", value1, value2, "sourceType");
            return (Criteria) this;
        }

        public Criteria andSourceTypeNotBetween(Integer value1, Integer value2) {
            addCriterion("source_type not between", value1, value2, "sourceType");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("status is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("status is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(Integer value) {
            addCriterion("status =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(Integer value) {
            addCriterion("status <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(Integer value) {
            addCriterion("status >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("status >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(Integer value) {
            addCriterion("status <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(Integer value) {
            addCriterion("status <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<Integer> values) {
            addCriterion("status in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<Integer> values) {
            addCriterion("status not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(Integer value1, Integer value2) {
            addCriterion("status between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("status not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("update_time is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("update_time is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(Date value) {
            addCriterion("update_time =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(Date value) {
            addCriterion("update_time <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(Date value) {
            addCriterion("update_time >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("update_time >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(Date value) {
            addCriterion("update_time <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("update_time <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<Date> values) {
            addCriterion("update_time in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<Date> values) {
            addCriterion("update_time not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("update_time between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("update_time not between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andProcesinstructionsIsNull() {
            addCriterion("procesInstructions is null");
            return (Criteria) this;
        }

        public Criteria andProcesinstructionsIsNotNull() {
            addCriterion("procesInstructions is not null");
            return (Criteria) this;
        }

        public Criteria andProcesinstructionsEqualTo(String value) {
            addCriterion("procesInstructions =", value, "procesinstructions");
            return (Criteria) this;
        }

        public Criteria andProcesinstructionsNotEqualTo(String value) {
            addCriterion("procesInstructions <>", value, "procesinstructions");
            return (Criteria) this;
        }

        public Criteria andProcesinstructionsGreaterThan(String value) {
            addCriterion("procesInstructions >", value, "procesinstructions");
            return (Criteria) this;
        }

        public Criteria andProcesinstructionsGreaterThanOrEqualTo(String value) {
            addCriterion("procesInstructions >=", value, "procesinstructions");
            return (Criteria) this;
        }

        public Criteria andProcesinstructionsLessThan(String value) {
            addCriterion("procesInstructions <", value, "procesinstructions");
            return (Criteria) this;
        }

        public Criteria andProcesinstructionsLessThanOrEqualTo(String value) {
            addCriterion("procesInstructions <=", value, "procesinstructions");
            return (Criteria) this;
        }

        public Criteria andProcesinstructionsLike(String value) {
            addCriterion("procesInstructions like", value, "procesinstructions");
            return (Criteria) this;
        }

        public Criteria andProcesinstructionsNotLike(String value) {
            addCriterion("procesInstructions not like", value, "procesinstructions");
            return (Criteria) this;
        }

        public Criteria andProcesinstructionsIn(List<String> values) {
            addCriterion("procesInstructions in", values, "procesinstructions");
            return (Criteria) this;
        }

        public Criteria andProcesinstructionsNotIn(List<String> values) {
            addCriterion("procesInstructions not in", values, "procesinstructions");
            return (Criteria) this;
        }

        public Criteria andProcesinstructionsBetween(String value1, String value2) {
            addCriterion("procesInstructions between", value1, value2, "procesinstructions");
            return (Criteria) this;
        }

        public Criteria andProcesinstructionsNotBetween(String value1, String value2) {
            addCriterion("procesInstructions not between", value1, value2, "procesinstructions");
            return (Criteria) this;
        }

        public Criteria andCallbackContentIsNull() {
            addCriterion("callback_content is null");
            return (Criteria) this;
        }

        public Criteria andCallbackContentIsNotNull() {
            addCriterion("callback_content is not null");
            return (Criteria) this;
        }

        public Criteria andCallbackContentEqualTo(String value) {
            addCriterion("callback_content =", value, "callbackContent");
            return (Criteria) this;
        }

        public Criteria andCallbackContentNotEqualTo(String value) {
            addCriterion("callback_content <>", value, "callbackContent");
            return (Criteria) this;
        }

        public Criteria andCallbackContentGreaterThan(String value) {
            addCriterion("callback_content >", value, "callbackContent");
            return (Criteria) this;
        }

        public Criteria andCallbackContentGreaterThanOrEqualTo(String value) {
            addCriterion("callback_content >=", value, "callbackContent");
            return (Criteria) this;
        }

        public Criteria andCallbackContentLessThan(String value) {
            addCriterion("callback_content <", value, "callbackContent");
            return (Criteria) this;
        }

        public Criteria andCallbackContentLessThanOrEqualTo(String value) {
            addCriterion("callback_content <=", value, "callbackContent");
            return (Criteria) this;
        }

        public Criteria andCallbackContentLike(String value) {
            addCriterion("callback_content like", value, "callbackContent");
            return (Criteria) this;
        }

        public Criteria andCallbackContentNotLike(String value) {
            addCriterion("callback_content not like", value, "callbackContent");
            return (Criteria) this;
        }

        public Criteria andCallbackContentIn(List<String> values) {
            addCriterion("callback_content in", values, "callbackContent");
            return (Criteria) this;
        }

        public Criteria andCallbackContentNotIn(List<String> values) {
            addCriterion("callback_content not in", values, "callbackContent");
            return (Criteria) this;
        }

        public Criteria andCallbackContentBetween(String value1, String value2) {
            addCriterion("callback_content between", value1, value2, "callbackContent");
            return (Criteria) this;
        }

        public Criteria andCallbackContentNotBetween(String value1, String value2) {
            addCriterion("callback_content not between", value1, value2, "callbackContent");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tc_order
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tc_order
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}