package com.everwing.coreservice.common.wy.entity.order;

import com.everwing.coreservice.common.Page;

import java.io.Serializable;
import java.util.Date;
/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table tc_order
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class TcOrder implements Serializable {
    private String searchDataProjectId;

    private Date searchDataStartTime;

    private Date searchDataEndTime;

    private String searchDataContent;

    private Page page;

    private String createBy;

    private String updateBy;

    private Date finishTime;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tc_order.order_id
     *
     * @mbg.generated
     */
    private String orderId;

    /**
     * Database Column Remarks:
     *   工单编号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tc_order.order_code
     *
     * @mbg.generated
     */
    private String orderCode;

    /**
     * Database Column Remarks:
     *   提出申请的个人客户
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tc_order.cust_id
     *
     * @mbg.generated
     */
    private String custId;

    /**
     * Database Column Remarks:
     *   提出申请的企业客户
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tc_order.cust_type
     *
     * @mbg.generated
     */
    private String custType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tc_order.building_code
     *
     * @mbg.generated
     */
    private String buildingCode;

    /**
     * Database Column Remarks:
     *   一级工单类型
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tc_order.order_type_id_1
     *
     * @mbg.generated
     */
    private String orderTypeId1;

    /**
     * Database Column Remarks:
     *   二级工单类型
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tc_order.order_type_id_2
     *
     * @mbg.generated
     */
    private String orderTypeId2;

    /**
     * Database Column Remarks:
     *   三级工单类型
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tc_order.order_type_id_3
     *
     * @mbg.generated
     */
    private String orderTypeId3;

    /**
     * Database Column Remarks:
     *   任务描述
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tc_order.description
     *
     * @mbg.generated
     */
    private String description;

    /**
     * Database Column Remarks:
     *   是否加急 0=false 1=true
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tc_order.is_urgent
     *
     * @mbg.generated
     */
    private Boolean isUrgent;

    /**
     * Database Column Remarks:
     *   负责人
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tc_order.principal_sys_user_id
     *
     * @mbg.generated
     */
    private String principalSysUserId;

    /**
     * Database Column Remarks:
     *   是否回访 0=false 1=true
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tc_order.need_callback
     *
     * @mbg.generated
     */
    private Boolean needCallback;

    /**
     * Database Column Remarks:
     *   1=前台 2=CC
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tc_order.source_type
     *
     * @mbg.generated
     */
    private Integer sourceType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tc_order.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     * Database Column Remarks:
     *   1=处理中 2=完成
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tc_order.status
     *
     * @mbg.generated
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tc_order.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tc_order.procesInstructions
     *
     * @mbg.generated
     */
    private String procesinstructions;

    /**
     * Database Column Remarks:
     *   回访信息
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tc_order.callback_content
     *
     * @mbg.generated
     */
    private String callbackContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tc_order
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tc_order.order_id
     *
     * @return the value of tc_order.order_id
     *
     * @mbg.generated
     */
    public String getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tc_order.order_id
     *
     * @param orderId the value for tc_order.order_id
     *
     * @mbg.generated
     */
    public void setOrderId(String orderId) {
        this.orderId = orderId == null ? null : orderId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tc_order.order_code
     *
     * @return the value of tc_order.order_code
     *
     * @mbg.generated
     */
    public String getOrderCode() {
        return orderCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tc_order.order_code
     *
     * @param orderCode the value for tc_order.order_code
     *
     * @mbg.generated
     */
    public void setOrderCode(String orderCode) {
        this.orderCode = orderCode == null ? null : orderCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tc_order.cust_id
     *
     * @return the value of tc_order.cust_id
     *
     * @mbg.generated
     */
    public String getCustId() {
        return custId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tc_order.cust_id
     *
     * @param custId the value for tc_order.cust_id
     *
     * @mbg.generated
     */
    public void setCustId(String custId) {
        this.custId = custId == null ? null : custId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tc_order.cust_type
     *
     * @return the value of tc_order.cust_type
     *
     * @mbg.generated
     */
    public String getCustType() {
        return custType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tc_order.cust_type
     *
     * @param custType the value for tc_order.cust_type
     *
     * @mbg.generated
     */
    public void setCustType(String custType) {
        this.custType = custType == null ? null : custType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tc_order.building_code
     *
     * @return the value of tc_order.building_code
     *
     * @mbg.generated
     */
    public String getBuildingCode() {
        return buildingCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tc_order.building_code
     *
     * @param buildingCode the value for tc_order.building_code
     *
     * @mbg.generated
     */
    public void setBuildingCode(String buildingCode) {
        this.buildingCode = buildingCode == null ? null : buildingCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tc_order.order_type_id_1
     *
     * @return the value of tc_order.order_type_id_1
     *
     * @mbg.generated
     */
    public String getOrderTypeId1() {
        return orderTypeId1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tc_order.order_type_id_1
     *
     * @param orderTypeId1 the value for tc_order.order_type_id_1
     *
     * @mbg.generated
     */
    public void setOrderTypeId1(String orderTypeId1) {
        this.orderTypeId1 = orderTypeId1 == null ? null : orderTypeId1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tc_order.order_type_id_2
     *
     * @return the value of tc_order.order_type_id_2
     *
     * @mbg.generated
     */
    public String getOrderTypeId2() {
        return orderTypeId2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tc_order.order_type_id_2
     *
     * @param orderTypeId2 the value for tc_order.order_type_id_2
     *
     * @mbg.generated
     */
    public void setOrderTypeId2(String orderTypeId2) {
        this.orderTypeId2 = orderTypeId2 == null ? null : orderTypeId2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tc_order.order_type_id_3
     *
     * @return the value of tc_order.order_type_id_3
     *
     * @mbg.generated
     */
    public String getOrderTypeId3() {
        return orderTypeId3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tc_order.order_type_id_3
     *
     * @param orderTypeId3 the value for tc_order.order_type_id_3
     *
     * @mbg.generated
     */
    public void setOrderTypeId3(String orderTypeId3) {
        this.orderTypeId3 = orderTypeId3 == null ? null : orderTypeId3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tc_order.description
     *
     * @return the value of tc_order.description
     *
     * @mbg.generated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tc_order.description
     *
     * @param description the value for tc_order.description
     *
     * @mbg.generated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tc_order.is_urgent
     *
     * @return the value of tc_order.is_urgent
     *
     * @mbg.generated
     */
    public Boolean getIsUrgent() {
        return isUrgent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tc_order.is_urgent
     *
     * @param isUrgent the value for tc_order.is_urgent
     *
     * @mbg.generated
     */
    public void setIsUrgent(Boolean isUrgent) {
        this.isUrgent = isUrgent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tc_order.principal_sys_user_id
     *
     * @return the value of tc_order.principal_sys_user_id
     *
     * @mbg.generated
     */
    public String getPrincipalSysUserId() {
        return principalSysUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tc_order.principal_sys_user_id
     *
     * @param principalSysUserId the value for tc_order.principal_sys_user_id
     *
     * @mbg.generated
     */
    public void setPrincipalSysUserId(String principalSysUserId) {
        this.principalSysUserId = principalSysUserId == null ? null : principalSysUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tc_order.need_callback
     *
     * @return the value of tc_order.need_callback
     *
     * @mbg.generated
     */
    public Boolean getNeedCallback() {
        return needCallback;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tc_order.need_callback
     *
     * @param needCallback the value for tc_order.need_callback
     *
     * @mbg.generated
     */
    public void setNeedCallback(Boolean needCallback) {
        this.needCallback = needCallback;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tc_order.source_type
     *
     * @return the value of tc_order.source_type
     *
     * @mbg.generated
     */
    public Integer getSourceType() {
        return sourceType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tc_order.source_type
     *
     * @param sourceType the value for tc_order.source_type
     *
     * @mbg.generated
     */
    public void setSourceType(Integer sourceType) {
        this.sourceType = sourceType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tc_order.create_time
     *
     * @return the value of tc_order.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tc_order.create_time
     *
     * @param createTime the value for tc_order.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tc_order.status
     *
     * @return the value of tc_order.status
     *
     * @mbg.generated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tc_order.status
     *
     * @param status the value for tc_order.status
     *
     * @mbg.generated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tc_order.update_time
     *
     * @return the value of tc_order.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tc_order.update_time
     *
     * @param updateTime the value for tc_order.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tc_order.procesInstructions
     *
     * @return the value of tc_order.procesInstructions
     *
     * @mbg.generated
     */
    public String getProcesinstructions() {
        return procesinstructions;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tc_order.procesInstructions
     *
     * @param procesinstructions the value for tc_order.procesInstructions
     *
     * @mbg.generated
     */
    public void setProcesinstructions(String procesinstructions) {
        this.procesinstructions = procesinstructions == null ? null : procesinstructions.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tc_order.callback_content
     *
     * @return the value of tc_order.callback_content
     *
     * @mbg.generated
     */
    public String getCallbackContent() {
        return callbackContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tc_order.callback_content
     *
     * @param callbackContent the value for tc_order.callback_content
     *
     * @mbg.generated
     */
    public void setCallbackContent(String callbackContent) {
        this.callbackContent = callbackContent == null ? null : callbackContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tc_order
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", orderId=").append(orderId);
        sb.append(", orderCode=").append(orderCode);
        sb.append(", custId=").append(custId);
        sb.append(", custType=").append(custType);
        sb.append(", buildingCode=").append(buildingCode);
        sb.append(", orderTypeId1=").append(orderTypeId1);
        sb.append(", orderTypeId2=").append(orderTypeId2);
        sb.append(", orderTypeId3=").append(orderTypeId3);
        sb.append(", description=").append(description);
        sb.append(", isUrgent=").append(isUrgent);
        sb.append(", principalSysUserId=").append(principalSysUserId);
        sb.append(", needCallback=").append(needCallback);
        sb.append(", sourceType=").append(sourceType);
        sb.append(", createTime=").append(createTime);
        sb.append(", status=").append(status);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", procesinstructions=").append(procesinstructions);
        sb.append(", callbackContent=").append(callbackContent);
        sb.append(", createBy=").append(createBy);
        sb.append(", updateBy=").append(updateBy);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }

	public String getSearchDataProjectId() {
		return searchDataProjectId;
	}

	public void setSearchDataProjectId(String searchDataProjectId) {
		this.searchDataProjectId = searchDataProjectId;
	}

	public Date getSearchDataStartTime() {
		return searchDataStartTime;
	}

	public void setSearchDataStartTime(Date searchDataStartTime) {
		this.searchDataStartTime = searchDataStartTime;
	}

	public Date getSearchDataEndTime() {
		return searchDataEndTime;
	}

	public void setSearchDataEndTime(Date searchDataEndTime) {
		this.searchDataEndTime = searchDataEndTime;
	}

	public String getSearchDataContent() {
		return searchDataContent;
	}

	public void setSearchDataContent(String searchDataContent) {
		this.searchDataContent = searchDataContent;
	}

	public Page getPage() {
		return page;
	}

	public void setPage(Page page) {
		this.page = page;
	}

    public String getCreateBy() {
        return createBy;
    }

    public void setCreateBy(String createBy) {
        this.createBy = createBy;
    }

    public String getUpdateBy() {
        return updateBy;
    }

    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy;
    }

    public Date getFinishTime() {
        return finishTime;
    }

    public void setFinishTime(Date finishTime) {
        this.finishTime = finishTime;
    }
}