package com.everwing.coreservice.common.wy.entity.account.pay;

import com.everwing.coreservice.common.Page;
import com.everwing.coreservice.common.wy.entity.annex.Annex;

import java.io.Serializable;
import java.util.Date;
import java.util.List;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table t_bs_pay_info
 *
 * @mbg.generated do_not_delete_during_merge Tue Oct 24 16:25:32 CST 2017
 */
public class TBsPayInfo implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bs_pay_info.id
     *
     * @mbg.generated Tue Oct 24 16:25:32 CST 2017
     */
    private String id;
    /**
     * 微信小程序
     */
    private  double wxXiao;
    /**
     * Database Column Remarks:
     *   项目id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bs_pay_info.project_id
     *
     * @mbg.generated Tue Oct 24 16:25:32 CST 2017
     */
    private String projectId;

    /**
     * Database Column Remarks:
     *   建筑code
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bs_pay_info.building_code
     *
     * @mbg.generated Tue Oct 24 16:25:32 CST 2017
     */
    private String buildingCode;

    /**
     * Database Column Remarks:
     *   建筑名
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bs_pay_info.building_full_name
     *
     * @mbg.generated Tue Oct 24 16:25:32 CST 2017
     */
    private String buildingFullName;

    /**
     * Database Column Remarks:
     *   资产编号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bs_pay_info.asset_no
     *
     * @mbg.generated Tue Oct 24 16:25:32 CST 2017
     */
    private String assetNo;

    /**
     * Database Column Remarks:
     *   客户名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bs_pay_info.cust_name
     *
     * @mbg.generated Tue Oct 24 16:25:32 CST 2017
     */
    private String custName;

    /**
     * Database Column Remarks:
     *   物业金额
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bs_pay_info.wy_amount
     *
     * @mbg.generated Tue Oct 24 16:25:32 CST 2017
     */
    private Double wyAmount;

    /**
     * Database Column Remarks:
     *   本体金额
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bs_pay_info.bt_amount
     *
     * @mbg.generated Tue Oct 24 16:25:32 CST 2017
     */
    private Double btAmount;

    /**
     * Database Column Remarks:
     *   水费金额
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bs_pay_info.water_amount
     *
     * @mbg.generated Tue Oct 24 16:25:32 CST 2017
     */
    private Double waterAmount;

    /**
     * Database Column Remarks:
     *   电费金额
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bs_pay_info.elect_amount
     *
     * @mbg.generated Tue Oct 24 16:25:32 CST 2017
     */
    private Double electAmount;

    /**
     * Database Column Remarks:
     *   通用账户金额
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bs_pay_info.common_amount
     *
     * @mbg.generated Tue Oct 24 16:25:32 CST 2017
     */
    private Double commonAmount;

    /**
     * Database Column Remarks:
     *   减免金额
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bs_pay_info.jm_amount
     *
     * @mbg.generated Tue Oct 24 16:25:32 CST 2017
     */
    private Double jmAmount;

    /**
     * Database Column Remarks:
     *   减免备注
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bs_pay_info.jm_remark
     *
     * @mbg.generated Tue Oct 24 16:25:32 CST 2017
     */
    private String jmRemark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bs_pay_info.create_time
     *
     * @mbg.generated Tue Oct 24 16:25:32 CST 2017
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bs_pay_info.create_id
     *
     * @mbg.generated Tue Oct 24 16:25:32 CST 2017
     */
    private String createId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bs_pay_info.modify_time
     *
     * @mbg.generated Tue Oct 24 16:25:32 CST 2017
     */
    private Date modifyTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bs_pay_info.modify_id
     *
     * @mbg.generated Tue Oct 24 16:25:32 CST 2017
     */
    private String modifyId;
    
    //物业税金
    private Double wyTax;

    //本体税金
    private Double btTax;
    
    //水费税金
    private Double waterTax;
    
    //电费税金
    private Double electTax;
    
    private Page page;
    
    //支付类型
    private Integer payType;
    
    //现金支付额
    private Double payCash;
    
    //微信支付额
    private Double payWx;
    
    //银联刷卡支付额
    private Double payUnion;
    
    //支付宝支付额
    private Double payZfb;
    
    //托收支付额
    private Double payColl;
    
    //银行支付额
    private Double payBank;
    
    //付款人名字
    private String payerName;
    
    //状态 0: 收款, 1: 退款
    private Integer status;
    
    //发票开具状态
    private Integer isGiveInvoice;
    
    //银账交割relationId
    private String relationId;
    
    //流水号
    private String batchNo;
    
    //发票附件
    private List<Annex> annexs;
    
    //辅助查询条件
    private List<String> buildingCodes;
    
    private String custId;
    
    private String custType;
    
    private Date startTime;
    
    private Date endTime;
    
    //辅助结果字段
    private Double totalLateFee;
    
    private Double wyLateFee;
    
    private Double btLateFee;
    
    private Double waterLateFee;
    
    private Double electLateFee;
    
    private String projectName;

    private String buildingType;

    private String phone;

    public String getPhone() {
        return phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }

    public double getWxXiao() {
        return wxXiao;
    }

    public void setWxXiao(double wxXiao) {
        this.wxXiao = wxXiao;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_bs_pay_info
     *
     * @mbg.generated Tue Oct 24 16:25:32 CST 2017
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bs_pay_info.id
     *
     * @return the value of t_bs_pay_info.id
     *
     * @mbg.generated Tue Oct 24 16:25:32 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bs_pay_info.id
     *
     * @param id the value for t_bs_pay_info.id
     *
     * @mbg.generated Tue Oct 24 16:25:32 CST 2017
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bs_pay_info.project_id
     *
     * @return the value of t_bs_pay_info.project_id
     *
     * @mbg.generated Tue Oct 24 16:25:32 CST 2017
     */
    public String getProjectId() {
        return projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bs_pay_info.project_id
     *
     * @param projectId the value for t_bs_pay_info.project_id
     *
     * @mbg.generated Tue Oct 24 16:25:32 CST 2017
     */
    public void setProjectId(String projectId) {
        this.projectId = projectId == null ? null : projectId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bs_pay_info.building_code
     *
     * @return the value of t_bs_pay_info.building_code
     *
     * @mbg.generated Tue Oct 24 16:25:32 CST 2017
     */
    public String getBuildingCode() {
        return buildingCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bs_pay_info.building_code
     *
     * @param buildingCode the value for t_bs_pay_info.building_code
     *
     * @mbg.generated Tue Oct 24 16:25:32 CST 2017
     */
    public void setBuildingCode(String buildingCode) {
        this.buildingCode = buildingCode == null ? null : buildingCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bs_pay_info.building_full_name
     *
     * @return the value of t_bs_pay_info.building_full_name
     *
     * @mbg.generated Tue Oct 24 16:25:32 CST 2017
     */
    public String getBuildingFullName() {
        return buildingFullName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bs_pay_info.building_full_name
     *
     * @param buildingFullName the value for t_bs_pay_info.building_full_name
     *
     * @mbg.generated Tue Oct 24 16:25:32 CST 2017
     */
    public void setBuildingFullName(String buildingFullName) {
        this.buildingFullName = buildingFullName == null ? null : buildingFullName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bs_pay_info.asset_no
     *
     * @return the value of t_bs_pay_info.asset_no
     *
     * @mbg.generated Tue Oct 24 16:25:32 CST 2017
     */
    public String getAssetNo() {
        return assetNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bs_pay_info.asset_no
     *
     * @param assetNo the value for t_bs_pay_info.asset_no
     *
     * @mbg.generated Tue Oct 24 16:25:32 CST 2017
     */
    public void setAssetNo(String assetNo) {
        this.assetNo = assetNo == null ? null : assetNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bs_pay_info.cust_name
     *
     * @return the value of t_bs_pay_info.cust_name
     *
     * @mbg.generated Tue Oct 24 16:25:32 CST 2017
     */
    public String getCustName() {
        return custName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bs_pay_info.cust_name
     *
     * @param custName the value for t_bs_pay_info.cust_name
     *
     * @mbg.generated Tue Oct 24 16:25:32 CST 2017
     */
    public void setCustName(String custName) {
        this.custName = custName == null ? null : custName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bs_pay_info.wy_amount
     *
     * @return the value of t_bs_pay_info.wy_amount
     *
     * @mbg.generated Tue Oct 24 16:25:32 CST 2017
     */
    public Double getWyAmount() {
        return wyAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bs_pay_info.wy_amount
     *
     * @param wyAmount the value for t_bs_pay_info.wy_amount
     *
     * @mbg.generated Tue Oct 24 16:25:32 CST 2017
     */
    public void setWyAmount(Double wyAmount) {
        this.wyAmount = wyAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bs_pay_info.bt_amount
     *
     * @return the value of t_bs_pay_info.bt_amount
     *
     * @mbg.generated Tue Oct 24 16:25:32 CST 2017
     */
    public Double getBtAmount() {
        return btAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bs_pay_info.bt_amount
     *
     * @param btAmount the value for t_bs_pay_info.bt_amount
     *
     * @mbg.generated Tue Oct 24 16:25:32 CST 2017
     */
    public void setBtAmount(Double btAmount) {
        this.btAmount = btAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bs_pay_info.water_amount
     *
     * @return the value of t_bs_pay_info.water_amount
     *
     * @mbg.generated Tue Oct 24 16:25:32 CST 2017
     */
    public Double getWaterAmount() {
        return waterAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bs_pay_info.water_amount
     *
     * @param waterAmount the value for t_bs_pay_info.water_amount
     *
     * @mbg.generated Tue Oct 24 16:25:32 CST 2017
     */
    public void setWaterAmount(Double waterAmount) {
        this.waterAmount = waterAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bs_pay_info.elect_amount
     *
     * @return the value of t_bs_pay_info.elect_amount
     *
     * @mbg.generated Tue Oct 24 16:25:32 CST 2017
     */
    public Double getElectAmount() {
        return electAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bs_pay_info.elect_amount
     *
     * @param electAmount the value for t_bs_pay_info.elect_amount
     *
     * @mbg.generated Tue Oct 24 16:25:32 CST 2017
     */
    public void setElectAmount(Double electAmount) {
        this.electAmount = electAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bs_pay_info.common_amount
     *
     * @return the value of t_bs_pay_info.common_amount
     *
     * @mbg.generated Tue Oct 24 16:25:32 CST 2017
     */
    public Double getCommonAmount() {
        return commonAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bs_pay_info.common_amount
     *
     * @param commonAmount the value for t_bs_pay_info.common_amount
     *
     * @mbg.generated Tue Oct 24 16:25:32 CST 2017
     */
    public void setCommonAmount(Double commonAmount) {
        this.commonAmount = commonAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bs_pay_info.jm_amount
     *
     * @return the value of t_bs_pay_info.jm_amount
     *
     * @mbg.generated Tue Oct 24 16:25:32 CST 2017
     */
    public Double getJmAmount() {
        return jmAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bs_pay_info.jm_amount
     *
     * @param jmAmount the value for t_bs_pay_info.jm_amount
     *
     * @mbg.generated Tue Oct 24 16:25:32 CST 2017
     */
    public void setJmAmount(Double jmAmount) {
        this.jmAmount = jmAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bs_pay_info.jm_remark
     *
     * @return the value of t_bs_pay_info.jm_remark
     *
     * @mbg.generated Tue Oct 24 16:25:32 CST 2017
     */
    public String getJmRemark() {
        return jmRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bs_pay_info.jm_remark
     *
     * @param jmRemark the value for t_bs_pay_info.jm_remark
     *
     * @mbg.generated Tue Oct 24 16:25:32 CST 2017
     */
    public void setJmRemark(String jmRemark) {
        this.jmRemark = jmRemark == null ? null : jmRemark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bs_pay_info.create_time
     *
     * @return the value of t_bs_pay_info.create_time
     *
     * @mbg.generated Tue Oct 24 16:25:32 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bs_pay_info.create_time
     *
     * @param createTime the value for t_bs_pay_info.create_time
     *
     * @mbg.generated Tue Oct 24 16:25:32 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bs_pay_info.create_id
     *
     * @return the value of t_bs_pay_info.create_id
     *
     * @mbg.generated Tue Oct 24 16:25:32 CST 2017
     */
    public String getCreateId() {
        return createId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bs_pay_info.create_id
     *
     * @param createId the value for t_bs_pay_info.create_id
     *
     * @mbg.generated Tue Oct 24 16:25:32 CST 2017
     */
    public void setCreateId(String createId) {
        this.createId = createId == null ? null : createId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bs_pay_info.modify_time
     *
     * @return the value of t_bs_pay_info.modify_time
     *
     * @mbg.generated Tue Oct 24 16:25:32 CST 2017
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bs_pay_info.modify_time
     *
     * @param modifyTime the value for t_bs_pay_info.modify_time
     *
     * @mbg.generated Tue Oct 24 16:25:32 CST 2017
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bs_pay_info.modify_id
     *
     * @return the value of t_bs_pay_info.modify_id
     *
     * @mbg.generated Tue Oct 24 16:25:32 CST 2017
     */
    public String getModifyId() {
        return modifyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bs_pay_info.modify_id
     *
     * @param modifyId the value for t_bs_pay_info.modify_id
     *
     * @mbg.generated Tue Oct 24 16:25:32 CST 2017
     */
    public void setModifyId(String modifyId) {
        this.modifyId = modifyId == null ? null : modifyId.trim();
    }

    public Page getPage() {
		return page;
	}

	public void setPage(Page page) {
		this.page = page;
	}

	public List<String> getBuildingCodes() {
		return buildingCodes;
	}

	public void setBuildingCodes(List<String> buildingCodes) {
		this.buildingCodes = buildingCodes;
	}

	public String getCustId() {
		return custId;
	}

	public void setCustId(String custId) {
		this.custId = custId;
	}

	public String getCustType() {
		return custType;
	}

	public void setCustType(String custType) {
		this.custType = custType;
	}

	public Double getWyTax() {
		return wyTax;
	}

	public void setWyTax(Double wyTax) {
		this.wyTax = wyTax;
	}

	public Double getBtTax() {
		return btTax;
	}

	public void setBtTax(Double btTax) {
		this.btTax = btTax;
	}

	public Double getWaterTax() {
		return waterTax;
	}

	public void setWaterTax(Double waterTax) {
		this.waterTax = waterTax;
	}

	public Double getElectTax() {
		return electTax;
	}

	public void setElectTax(Double electTax) {
		this.electTax = electTax;
	}

	public Integer getPayType() {
		return payType;
	}

	public void setPayType(Integer payType) {
		this.payType = payType;
	}

	public Double getPayCash() {
		return payCash;
	}

	public void setPayCash(Double payCash) {
		this.payCash = payCash;
	}

	public Double getPayWx() {
		return payWx;
	}

	public void setPayWx(Double payWx) {
		this.payWx = payWx;
	}

	public Double getPayUnion() {
		return payUnion;
	}

	public void setPayUnion(Double payUnion) {
		this.payUnion = payUnion;
	}

	public Double getPayZfb() {
		return payZfb;
	}

	public void setPayZfb(Double payZfb) {
		this.payZfb = payZfb;
	}

	public String getPayerName() {
		return payerName;
	}

	public void setPayerName(String payerName) {
		this.payerName = payerName;
	}

	public Double getTotalLateFee() {
		return totalLateFee;
	}

	public void setTotalLateFee(Double totalLateFee) {
		this.totalLateFee = totalLateFee;
	}

	public Integer getStatus() {
		return status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	public Date getStartTime() {
		return startTime;
	}

	public void setStartTime(Date startTime) {
		this.startTime = startTime;
	}

	public Date getEndTime() {
		return endTime;
	}

	public void setEndTime(Date endTime) {
		this.endTime = endTime;
	}

	public Integer getIsGiveInvoice() {
		return isGiveInvoice;
	}

	public void setIsGiveInvoice(Integer isGiveInvoice) {
		this.isGiveInvoice = isGiveInvoice;
	}

	public List<Annex> getAnnexs() {
		return annexs;
	}

	public void setAnnexs(List<Annex> annexs) {
		this.annexs = annexs;
	}

	public String getBatchNo() {
		return batchNo;
	}

	public void setBatchNo(String batchNo) {
		this.batchNo = batchNo;
	}

	public String getRelationId() {
		return relationId;
	}

	public void setRelationId(String relationId) {
		this.relationId = relationId;
	}

	public Double getWyLateFee() {
		return wyLateFee;
	}

	public void setWyLateFee(Double wyLateFee) {
		this.wyLateFee = wyLateFee;
	}

	public Double getBtLateFee() {
		return btLateFee;
	}

	public void setBtLateFee(Double btLateFee) {
		this.btLateFee = btLateFee;
	}

	public Double getWaterLateFee() {
		return waterLateFee;
	}

	public void setWaterLateFee(Double waterLateFee) {
		this.waterLateFee = waterLateFee;
	}

	public Double getElectLateFee() {
		return electLateFee;
	}

	public void setElectLateFee(Double electLateFee) {
		this.electLateFee = electLateFee;
	}

	public Double getPayColl() {
		return payColl;
	}

	public void setPayColl(Double payColl) {
		this.payColl = payColl;
	}

	public Double getPayBank() {
		return payBank;
	}

	public void setPayBank(Double payBank) {
		this.payBank = payBank;
	}

    public String getBuildingType() {
        return buildingType;
    }

    public void setBuildingType(String buildingType) {
        this.buildingType = buildingType;
    }

    @Override
	public String toString() {
		final int maxLen = 10;
		return "TBsPayInfo [id="
				+ id
				+ ", projectId="
				+ projectId
				+ ", buildingCode="
				+ buildingCode
				+ ", buildingFullName="
				+ buildingFullName
				+ ", assetNo="
				+ assetNo
				+ ", custName="
				+ custName
				+ ", wyAmount="
				+ wyAmount
				+ ", btAmount="
				+ btAmount
				+ ", waterAmount="
				+ waterAmount
				+ ", electAmount="
				+ electAmount
				+ ", commonAmount="
				+ commonAmount
				+ ", jmAmount="
				+ jmAmount
				+ ", jmRemark="
				+ jmRemark
				+ ", createTime="
				+ createTime
				+ ", createId="
				+ createId
				+ ", modifyTime="
				+ modifyTime
				+ ", modifyId="
				+ modifyId
				+ ", wyTax="
				+ wyTax
				+ ", btTax="
				+ btTax
				+ ", waterTax="
				+ waterTax
				+ ", electTax="
				+ electTax
				+ ", page="
				+ page
				+ ", payType="
				+ payType
				+ ", payCash="
				+ payCash
				+ ", payWx="
				+ payWx
				+ ", payUnion="
				+ payUnion
				+ ", payZfb="
				+ payZfb
				+ ", payColl="
				+ payColl
				+ ", payBank="
				+ payBank
				+ ", payerName="
				+ payerName
				+ ", status="
				+ status
				+ ", isGiveInvoice="
				+ isGiveInvoice
				+ ", relationId="
				+ relationId
				+ ", batchNo="
				+ batchNo
				+ ", annexs="
				+ (annexs != null ? annexs.subList(0,
						Math.min(annexs.size(), maxLen)) : null)
				+ ", buildingCodes="
				+ (buildingCodes != null ? buildingCodes.subList(0,
						Math.min(buildingCodes.size(), maxLen)) : null)
				+ ", custId=" + custId + ", custType=" + custType
				+ ", startTime=" + startTime + ", endTime=" + endTime
				+ ", totalLateFee=" + totalLateFee + ", wyLateFee=" + wyLateFee
				+ ", btLateFee=" + btLateFee + ", waterLateFee=" + waterLateFee
				+ ", electLateFee=" + electLateFee + "]";
	}

	public String getProjectName() {
		return projectName;
	}

	public void setProjectName(String projectName) {
		this.projectName = projectName;
	}

	
}