package com.everwing.coreservice.common.wy.entity.account.pay;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class TBsPayInfoExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_bs_pay_info
     *
     * @mbg.generated Tue Oct 24 16:25:32 CST 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_bs_pay_info
     *
     * @mbg.generated Tue Oct 24 16:25:32 CST 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_bs_pay_info
     *
     * @mbg.generated Tue Oct 24 16:25:32 CST 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_bs_pay_info
     *
     * @mbg.generated Tue Oct 24 16:25:32 CST 2017
     */
    protected int limitStart = -1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_bs_pay_info
     *
     * @mbg.generated Tue Oct 24 16:25:32 CST 2017
     */
    protected int limitEnd = -1;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bs_pay_info
     *
     * @mbg.generated Tue Oct 24 16:25:32 CST 2017
     */
    public TBsPayInfoExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bs_pay_info
     *
     * @mbg.generated Tue Oct 24 16:25:32 CST 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bs_pay_info
     *
     * @mbg.generated Tue Oct 24 16:25:32 CST 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bs_pay_info
     *
     * @mbg.generated Tue Oct 24 16:25:32 CST 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bs_pay_info
     *
     * @mbg.generated Tue Oct 24 16:25:32 CST 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bs_pay_info
     *
     * @mbg.generated Tue Oct 24 16:25:32 CST 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bs_pay_info
     *
     * @mbg.generated Tue Oct 24 16:25:32 CST 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bs_pay_info
     *
     * @mbg.generated Tue Oct 24 16:25:32 CST 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bs_pay_info
     *
     * @mbg.generated Tue Oct 24 16:25:32 CST 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bs_pay_info
     *
     * @mbg.generated Tue Oct 24 16:25:32 CST 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bs_pay_info
     *
     * @mbg.generated Tue Oct 24 16:25:32 CST 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bs_pay_info
     *
     * @mbg.generated Tue Oct 24 16:25:32 CST 2017
     */
    public void setLimitStart(int limitStart) {
        this.limitStart=limitStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bs_pay_info
     *
     * @mbg.generated Tue Oct 24 16:25:32 CST 2017
     */
    public int getLimitStart() {
        return limitStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bs_pay_info
     *
     * @mbg.generated Tue Oct 24 16:25:32 CST 2017
     */
    public void setLimitEnd(int limitEnd) {
        this.limitEnd=limitEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bs_pay_info
     *
     * @mbg.generated Tue Oct 24 16:25:32 CST 2017
     */
    public int getLimitEnd() {
        return limitEnd;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_bs_pay_info
     *
     * @mbg.generated Tue Oct 24 16:25:32 CST 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(String value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(String value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(String value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(String value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(String value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(String value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLike(String value) {
            addCriterion("id like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotLike(String value) {
            addCriterion("id not like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<String> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<String> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(String value1, String value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(String value1, String value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andProjectIdIsNull() {
            addCriterion("project_id is null");
            return (Criteria) this;
        }

        public Criteria andProjectIdIsNotNull() {
            addCriterion("project_id is not null");
            return (Criteria) this;
        }

        public Criteria andProjectIdEqualTo(String value) {
            addCriterion("project_id =", value, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdNotEqualTo(String value) {
            addCriterion("project_id <>", value, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdGreaterThan(String value) {
            addCriterion("project_id >", value, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdGreaterThanOrEqualTo(String value) {
            addCriterion("project_id >=", value, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdLessThan(String value) {
            addCriterion("project_id <", value, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdLessThanOrEqualTo(String value) {
            addCriterion("project_id <=", value, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdLike(String value) {
            addCriterion("project_id like", value, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdNotLike(String value) {
            addCriterion("project_id not like", value, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdIn(List<String> values) {
            addCriterion("project_id in", values, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdNotIn(List<String> values) {
            addCriterion("project_id not in", values, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdBetween(String value1, String value2) {
            addCriterion("project_id between", value1, value2, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdNotBetween(String value1, String value2) {
            addCriterion("project_id not between", value1, value2, "projectId");
            return (Criteria) this;
        }

        public Criteria andBuildingCodeIsNull() {
            addCriterion("building_code is null");
            return (Criteria) this;
        }

        public Criteria andBuildingCodeIsNotNull() {
            addCriterion("building_code is not null");
            return (Criteria) this;
        }

        public Criteria andBuildingCodeEqualTo(String value) {
            addCriterion("building_code =", value, "buildingCode");
            return (Criteria) this;
        }

        public Criteria andBuildingCodeNotEqualTo(String value) {
            addCriterion("building_code <>", value, "buildingCode");
            return (Criteria) this;
        }

        public Criteria andBuildingCodeGreaterThan(String value) {
            addCriterion("building_code >", value, "buildingCode");
            return (Criteria) this;
        }

        public Criteria andBuildingCodeGreaterThanOrEqualTo(String value) {
            addCriterion("building_code >=", value, "buildingCode");
            return (Criteria) this;
        }

        public Criteria andBuildingCodeLessThan(String value) {
            addCriterion("building_code <", value, "buildingCode");
            return (Criteria) this;
        }

        public Criteria andBuildingCodeLessThanOrEqualTo(String value) {
            addCriterion("building_code <=", value, "buildingCode");
            return (Criteria) this;
        }

        public Criteria andBuildingCodeLike(String value) {
            addCriterion("building_code like", value, "buildingCode");
            return (Criteria) this;
        }

        public Criteria andBuildingCodeNotLike(String value) {
            addCriterion("building_code not like", value, "buildingCode");
            return (Criteria) this;
        }

        public Criteria andBuildingCodeIn(List<String> values) {
            addCriterion("building_code in", values, "buildingCode");
            return (Criteria) this;
        }

        public Criteria andBuildingCodeNotIn(List<String> values) {
            addCriterion("building_code not in", values, "buildingCode");
            return (Criteria) this;
        }

        public Criteria andBuildingCodeBetween(String value1, String value2) {
            addCriterion("building_code between", value1, value2, "buildingCode");
            return (Criteria) this;
        }

        public Criteria andBuildingCodeNotBetween(String value1, String value2) {
            addCriterion("building_code not between", value1, value2, "buildingCode");
            return (Criteria) this;
        }

        public Criteria andBuildingFullNameIsNull() {
            addCriterion("building_full_name is null");
            return (Criteria) this;
        }

        public Criteria andBuildingFullNameIsNotNull() {
            addCriterion("building_full_name is not null");
            return (Criteria) this;
        }

        public Criteria andBuildingFullNameEqualTo(String value) {
            addCriterion("building_full_name =", value, "buildingFullName");
            return (Criteria) this;
        }

        public Criteria andBuildingFullNameNotEqualTo(String value) {
            addCriterion("building_full_name <>", value, "buildingFullName");
            return (Criteria) this;
        }

        public Criteria andBuildingFullNameGreaterThan(String value) {
            addCriterion("building_full_name >", value, "buildingFullName");
            return (Criteria) this;
        }

        public Criteria andBuildingFullNameGreaterThanOrEqualTo(String value) {
            addCriterion("building_full_name >=", value, "buildingFullName");
            return (Criteria) this;
        }

        public Criteria andBuildingFullNameLessThan(String value) {
            addCriterion("building_full_name <", value, "buildingFullName");
            return (Criteria) this;
        }

        public Criteria andBuildingFullNameLessThanOrEqualTo(String value) {
            addCriterion("building_full_name <=", value, "buildingFullName");
            return (Criteria) this;
        }

        public Criteria andBuildingFullNameLike(String value) {
            addCriterion("building_full_name like", value, "buildingFullName");
            return (Criteria) this;
        }

        public Criteria andBuildingFullNameNotLike(String value) {
            addCriterion("building_full_name not like", value, "buildingFullName");
            return (Criteria) this;
        }

        public Criteria andBuildingFullNameIn(List<String> values) {
            addCriterion("building_full_name in", values, "buildingFullName");
            return (Criteria) this;
        }

        public Criteria andBuildingFullNameNotIn(List<String> values) {
            addCriterion("building_full_name not in", values, "buildingFullName");
            return (Criteria) this;
        }

        public Criteria andBuildingFullNameBetween(String value1, String value2) {
            addCriterion("building_full_name between", value1, value2, "buildingFullName");
            return (Criteria) this;
        }

        public Criteria andBuildingFullNameNotBetween(String value1, String value2) {
            addCriterion("building_full_name not between", value1, value2, "buildingFullName");
            return (Criteria) this;
        }

        public Criteria andAssetNoIsNull() {
            addCriterion("asset_no is null");
            return (Criteria) this;
        }

        public Criteria andAssetNoIsNotNull() {
            addCriterion("asset_no is not null");
            return (Criteria) this;
        }

        public Criteria andAssetNoEqualTo(String value) {
            addCriterion("asset_no =", value, "assetNo");
            return (Criteria) this;
        }

        public Criteria andAssetNoNotEqualTo(String value) {
            addCriterion("asset_no <>", value, "assetNo");
            return (Criteria) this;
        }

        public Criteria andAssetNoGreaterThan(String value) {
            addCriterion("asset_no >", value, "assetNo");
            return (Criteria) this;
        }

        public Criteria andAssetNoGreaterThanOrEqualTo(String value) {
            addCriterion("asset_no >=", value, "assetNo");
            return (Criteria) this;
        }

        public Criteria andAssetNoLessThan(String value) {
            addCriterion("asset_no <", value, "assetNo");
            return (Criteria) this;
        }

        public Criteria andAssetNoLessThanOrEqualTo(String value) {
            addCriterion("asset_no <=", value, "assetNo");
            return (Criteria) this;
        }

        public Criteria andAssetNoLike(String value) {
            addCriterion("asset_no like", value, "assetNo");
            return (Criteria) this;
        }

        public Criteria andAssetNoNotLike(String value) {
            addCriterion("asset_no not like", value, "assetNo");
            return (Criteria) this;
        }

        public Criteria andAssetNoIn(List<String> values) {
            addCriterion("asset_no in", values, "assetNo");
            return (Criteria) this;
        }

        public Criteria andAssetNoNotIn(List<String> values) {
            addCriterion("asset_no not in", values, "assetNo");
            return (Criteria) this;
        }

        public Criteria andAssetNoBetween(String value1, String value2) {
            addCriterion("asset_no between", value1, value2, "assetNo");
            return (Criteria) this;
        }

        public Criteria andAssetNoNotBetween(String value1, String value2) {
            addCriterion("asset_no not between", value1, value2, "assetNo");
            return (Criteria) this;
        }

        public Criteria andCustNameIsNull() {
            addCriterion("cust_name is null");
            return (Criteria) this;
        }

        public Criteria andCustNameIsNotNull() {
            addCriterion("cust_name is not null");
            return (Criteria) this;
        }

        public Criteria andCustNameEqualTo(String value) {
            addCriterion("cust_name =", value, "custName");
            return (Criteria) this;
        }

        public Criteria andCustNameNotEqualTo(String value) {
            addCriterion("cust_name <>", value, "custName");
            return (Criteria) this;
        }

        public Criteria andCustNameGreaterThan(String value) {
            addCriterion("cust_name >", value, "custName");
            return (Criteria) this;
        }

        public Criteria andCustNameGreaterThanOrEqualTo(String value) {
            addCriterion("cust_name >=", value, "custName");
            return (Criteria) this;
        }

        public Criteria andCustNameLessThan(String value) {
            addCriterion("cust_name <", value, "custName");
            return (Criteria) this;
        }

        public Criteria andCustNameLessThanOrEqualTo(String value) {
            addCriterion("cust_name <=", value, "custName");
            return (Criteria) this;
        }

        public Criteria andCustNameLike(String value) {
            addCriterion("cust_name like", value, "custName");
            return (Criteria) this;
        }

        public Criteria andCustNameNotLike(String value) {
            addCriterion("cust_name not like", value, "custName");
            return (Criteria) this;
        }

        public Criteria andCustNameIn(List<String> values) {
            addCriterion("cust_name in", values, "custName");
            return (Criteria) this;
        }

        public Criteria andCustNameNotIn(List<String> values) {
            addCriterion("cust_name not in", values, "custName");
            return (Criteria) this;
        }

        public Criteria andCustNameBetween(String value1, String value2) {
            addCriterion("cust_name between", value1, value2, "custName");
            return (Criteria) this;
        }

        public Criteria andCustNameNotBetween(String value1, String value2) {
            addCriterion("cust_name not between", value1, value2, "custName");
            return (Criteria) this;
        }

        public Criteria andWyAmountIsNull() {
            addCriterion("wy_amount is null");
            return (Criteria) this;
        }

        public Criteria andWyAmountIsNotNull() {
            addCriterion("wy_amount is not null");
            return (Criteria) this;
        }

        public Criteria andWyAmountEqualTo(Double value) {
            addCriterion("wy_amount =", value, "wyAmount");
            return (Criteria) this;
        }

        public Criteria andWyAmountNotEqualTo(Double value) {
            addCriterion("wy_amount <>", value, "wyAmount");
            return (Criteria) this;
        }

        public Criteria andWyAmountGreaterThan(Double value) {
            addCriterion("wy_amount >", value, "wyAmount");
            return (Criteria) this;
        }

        public Criteria andWyAmountGreaterThanOrEqualTo(Double value) {
            addCriterion("wy_amount >=", value, "wyAmount");
            return (Criteria) this;
        }

        public Criteria andWyAmountLessThan(Double value) {
            addCriterion("wy_amount <", value, "wyAmount");
            return (Criteria) this;
        }

        public Criteria andWyAmountLessThanOrEqualTo(Double value) {
            addCriterion("wy_amount <=", value, "wyAmount");
            return (Criteria) this;
        }

        public Criteria andWyAmountIn(List<Double> values) {
            addCriterion("wy_amount in", values, "wyAmount");
            return (Criteria) this;
        }

        public Criteria andWyAmountNotIn(List<Double> values) {
            addCriterion("wy_amount not in", values, "wyAmount");
            return (Criteria) this;
        }

        public Criteria andWyAmountBetween(Double value1, Double value2) {
            addCriterion("wy_amount between", value1, value2, "wyAmount");
            return (Criteria) this;
        }

        public Criteria andWyAmountNotBetween(Double value1, Double value2) {
            addCriterion("wy_amount not between", value1, value2, "wyAmount");
            return (Criteria) this;
        }

        public Criteria andBtAmountIsNull() {
            addCriterion("bt_amount is null");
            return (Criteria) this;
        }

        public Criteria andBtAmountIsNotNull() {
            addCriterion("bt_amount is not null");
            return (Criteria) this;
        }

        public Criteria andBtAmountEqualTo(Double value) {
            addCriterion("bt_amount =", value, "btAmount");
            return (Criteria) this;
        }

        public Criteria andBtAmountNotEqualTo(Double value) {
            addCriterion("bt_amount <>", value, "btAmount");
            return (Criteria) this;
        }

        public Criteria andBtAmountGreaterThan(Double value) {
            addCriterion("bt_amount >", value, "btAmount");
            return (Criteria) this;
        }

        public Criteria andBtAmountGreaterThanOrEqualTo(Double value) {
            addCriterion("bt_amount >=", value, "btAmount");
            return (Criteria) this;
        }

        public Criteria andBtAmountLessThan(Double value) {
            addCriterion("bt_amount <", value, "btAmount");
            return (Criteria) this;
        }

        public Criteria andBtAmountLessThanOrEqualTo(Double value) {
            addCriterion("bt_amount <=", value, "btAmount");
            return (Criteria) this;
        }

        public Criteria andBtAmountIn(List<Double> values) {
            addCriterion("bt_amount in", values, "btAmount");
            return (Criteria) this;
        }

        public Criteria andBtAmountNotIn(List<Double> values) {
            addCriterion("bt_amount not in", values, "btAmount");
            return (Criteria) this;
        }

        public Criteria andBtAmountBetween(Double value1, Double value2) {
            addCriterion("bt_amount between", value1, value2, "btAmount");
            return (Criteria) this;
        }

        public Criteria andBtAmountNotBetween(Double value1, Double value2) {
            addCriterion("bt_amount not between", value1, value2, "btAmount");
            return (Criteria) this;
        }

        public Criteria andWaterAmountIsNull() {
            addCriterion("water_amount is null");
            return (Criteria) this;
        }

        public Criteria andWaterAmountIsNotNull() {
            addCriterion("water_amount is not null");
            return (Criteria) this;
        }

        public Criteria andWaterAmountEqualTo(Double value) {
            addCriterion("water_amount =", value, "waterAmount");
            return (Criteria) this;
        }

        public Criteria andWaterAmountNotEqualTo(Double value) {
            addCriterion("water_amount <>", value, "waterAmount");
            return (Criteria) this;
        }

        public Criteria andWaterAmountGreaterThan(Double value) {
            addCriterion("water_amount >", value, "waterAmount");
            return (Criteria) this;
        }

        public Criteria andWaterAmountGreaterThanOrEqualTo(Double value) {
            addCriterion("water_amount >=", value, "waterAmount");
            return (Criteria) this;
        }

        public Criteria andWaterAmountLessThan(Double value) {
            addCriterion("water_amount <", value, "waterAmount");
            return (Criteria) this;
        }

        public Criteria andWaterAmountLessThanOrEqualTo(Double value) {
            addCriterion("water_amount <=", value, "waterAmount");
            return (Criteria) this;
        }

        public Criteria andWaterAmountIn(List<Double> values) {
            addCriterion("water_amount in", values, "waterAmount");
            return (Criteria) this;
        }

        public Criteria andWaterAmountNotIn(List<Double> values) {
            addCriterion("water_amount not in", values, "waterAmount");
            return (Criteria) this;
        }

        public Criteria andWaterAmountBetween(Double value1, Double value2) {
            addCriterion("water_amount between", value1, value2, "waterAmount");
            return (Criteria) this;
        }

        public Criteria andWaterAmountNotBetween(Double value1, Double value2) {
            addCriterion("water_amount not between", value1, value2, "waterAmount");
            return (Criteria) this;
        }

        public Criteria andElectAmountIsNull() {
            addCriterion("elect_amount is null");
            return (Criteria) this;
        }

        public Criteria andElectAmountIsNotNull() {
            addCriterion("elect_amount is not null");
            return (Criteria) this;
        }

        public Criteria andElectAmountEqualTo(Double value) {
            addCriterion("elect_amount =", value, "electAmount");
            return (Criteria) this;
        }

        public Criteria andElectAmountNotEqualTo(Double value) {
            addCriterion("elect_amount <>", value, "electAmount");
            return (Criteria) this;
        }

        public Criteria andElectAmountGreaterThan(Double value) {
            addCriterion("elect_amount >", value, "electAmount");
            return (Criteria) this;
        }

        public Criteria andElectAmountGreaterThanOrEqualTo(Double value) {
            addCriterion("elect_amount >=", value, "electAmount");
            return (Criteria) this;
        }

        public Criteria andElectAmountLessThan(Double value) {
            addCriterion("elect_amount <", value, "electAmount");
            return (Criteria) this;
        }

        public Criteria andElectAmountLessThanOrEqualTo(Double value) {
            addCriterion("elect_amount <=", value, "electAmount");
            return (Criteria) this;
        }

        public Criteria andElectAmountIn(List<Double> values) {
            addCriterion("elect_amount in", values, "electAmount");
            return (Criteria) this;
        }

        public Criteria andElectAmountNotIn(List<Double> values) {
            addCriterion("elect_amount not in", values, "electAmount");
            return (Criteria) this;
        }

        public Criteria andElectAmountBetween(Double value1, Double value2) {
            addCriterion("elect_amount between", value1, value2, "electAmount");
            return (Criteria) this;
        }

        public Criteria andElectAmountNotBetween(Double value1, Double value2) {
            addCriterion("elect_amount not between", value1, value2, "electAmount");
            return (Criteria) this;
        }

        public Criteria andCommonAmountIsNull() {
            addCriterion("common_amount is null");
            return (Criteria) this;
        }

        public Criteria andCommonAmountIsNotNull() {
            addCriterion("common_amount is not null");
            return (Criteria) this;
        }

        public Criteria andCommonAmountEqualTo(Double value) {
            addCriterion("common_amount =", value, "commonAmount");
            return (Criteria) this;
        }

        public Criteria andCommonAmountNotEqualTo(Double value) {
            addCriterion("common_amount <>", value, "commonAmount");
            return (Criteria) this;
        }

        public Criteria andCommonAmountGreaterThan(Double value) {
            addCriterion("common_amount >", value, "commonAmount");
            return (Criteria) this;
        }

        public Criteria andCommonAmountGreaterThanOrEqualTo(Double value) {
            addCriterion("common_amount >=", value, "commonAmount");
            return (Criteria) this;
        }

        public Criteria andCommonAmountLessThan(Double value) {
            addCriterion("common_amount <", value, "commonAmount");
            return (Criteria) this;
        }

        public Criteria andCommonAmountLessThanOrEqualTo(Double value) {
            addCriterion("common_amount <=", value, "commonAmount");
            return (Criteria) this;
        }

        public Criteria andCommonAmountIn(List<Double> values) {
            addCriterion("common_amount in", values, "commonAmount");
            return (Criteria) this;
        }

        public Criteria andCommonAmountNotIn(List<Double> values) {
            addCriterion("common_amount not in", values, "commonAmount");
            return (Criteria) this;
        }

        public Criteria andCommonAmountBetween(Double value1, Double value2) {
            addCriterion("common_amount between", value1, value2, "commonAmount");
            return (Criteria) this;
        }

        public Criteria andCommonAmountNotBetween(Double value1, Double value2) {
            addCriterion("common_amount not between", value1, value2, "commonAmount");
            return (Criteria) this;
        }

        public Criteria andJmAmountIsNull() {
            addCriterion("jm_amount is null");
            return (Criteria) this;
        }

        public Criteria andJmAmountIsNotNull() {
            addCriterion("jm_amount is not null");
            return (Criteria) this;
        }

        public Criteria andJmAmountEqualTo(Double value) {
            addCriterion("jm_amount =", value, "jmAmount");
            return (Criteria) this;
        }

        public Criteria andJmAmountNotEqualTo(Double value) {
            addCriterion("jm_amount <>", value, "jmAmount");
            return (Criteria) this;
        }

        public Criteria andJmAmountGreaterThan(Double value) {
            addCriterion("jm_amount >", value, "jmAmount");
            return (Criteria) this;
        }

        public Criteria andJmAmountGreaterThanOrEqualTo(Double value) {
            addCriterion("jm_amount >=", value, "jmAmount");
            return (Criteria) this;
        }

        public Criteria andJmAmountLessThan(Double value) {
            addCriterion("jm_amount <", value, "jmAmount");
            return (Criteria) this;
        }

        public Criteria andJmAmountLessThanOrEqualTo(Double value) {
            addCriterion("jm_amount <=", value, "jmAmount");
            return (Criteria) this;
        }

        public Criteria andJmAmountIn(List<Double> values) {
            addCriterion("jm_amount in", values, "jmAmount");
            return (Criteria) this;
        }

        public Criteria andJmAmountNotIn(List<Double> values) {
            addCriterion("jm_amount not in", values, "jmAmount");
            return (Criteria) this;
        }

        public Criteria andJmAmountBetween(Double value1, Double value2) {
            addCriterion("jm_amount between", value1, value2, "jmAmount");
            return (Criteria) this;
        }

        public Criteria andJmAmountNotBetween(Double value1, Double value2) {
            addCriterion("jm_amount not between", value1, value2, "jmAmount");
            return (Criteria) this;
        }

        public Criteria andJmRemarkIsNull() {
            addCriterion("jm_remark is null");
            return (Criteria) this;
        }

        public Criteria andJmRemarkIsNotNull() {
            addCriterion("jm_remark is not null");
            return (Criteria) this;
        }

        public Criteria andJmRemarkEqualTo(String value) {
            addCriterion("jm_remark =", value, "jmRemark");
            return (Criteria) this;
        }

        public Criteria andJmRemarkNotEqualTo(String value) {
            addCriterion("jm_remark <>", value, "jmRemark");
            return (Criteria) this;
        }

        public Criteria andJmRemarkGreaterThan(String value) {
            addCriterion("jm_remark >", value, "jmRemark");
            return (Criteria) this;
        }

        public Criteria andJmRemarkGreaterThanOrEqualTo(String value) {
            addCriterion("jm_remark >=", value, "jmRemark");
            return (Criteria) this;
        }

        public Criteria andJmRemarkLessThan(String value) {
            addCriterion("jm_remark <", value, "jmRemark");
            return (Criteria) this;
        }

        public Criteria andJmRemarkLessThanOrEqualTo(String value) {
            addCriterion("jm_remark <=", value, "jmRemark");
            return (Criteria) this;
        }

        public Criteria andJmRemarkLike(String value) {
            addCriterion("jm_remark like", value, "jmRemark");
            return (Criteria) this;
        }

        public Criteria andJmRemarkNotLike(String value) {
            addCriterion("jm_remark not like", value, "jmRemark");
            return (Criteria) this;
        }

        public Criteria andJmRemarkIn(List<String> values) {
            addCriterion("jm_remark in", values, "jmRemark");
            return (Criteria) this;
        }

        public Criteria andJmRemarkNotIn(List<String> values) {
            addCriterion("jm_remark not in", values, "jmRemark");
            return (Criteria) this;
        }

        public Criteria andJmRemarkBetween(String value1, String value2) {
            addCriterion("jm_remark between", value1, value2, "jmRemark");
            return (Criteria) this;
        }

        public Criteria andJmRemarkNotBetween(String value1, String value2) {
            addCriterion("jm_remark not between", value1, value2, "jmRemark");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateIdIsNull() {
            addCriterion("create_id is null");
            return (Criteria) this;
        }

        public Criteria andCreateIdIsNotNull() {
            addCriterion("create_id is not null");
            return (Criteria) this;
        }

        public Criteria andCreateIdEqualTo(String value) {
            addCriterion("create_id =", value, "createId");
            return (Criteria) this;
        }

        public Criteria andCreateIdNotEqualTo(String value) {
            addCriterion("create_id <>", value, "createId");
            return (Criteria) this;
        }

        public Criteria andCreateIdGreaterThan(String value) {
            addCriterion("create_id >", value, "createId");
            return (Criteria) this;
        }

        public Criteria andCreateIdGreaterThanOrEqualTo(String value) {
            addCriterion("create_id >=", value, "createId");
            return (Criteria) this;
        }

        public Criteria andCreateIdLessThan(String value) {
            addCriterion("create_id <", value, "createId");
            return (Criteria) this;
        }

        public Criteria andCreateIdLessThanOrEqualTo(String value) {
            addCriterion("create_id <=", value, "createId");
            return (Criteria) this;
        }

        public Criteria andCreateIdLike(String value) {
            addCriterion("create_id like", value, "createId");
            return (Criteria) this;
        }

        public Criteria andCreateIdNotLike(String value) {
            addCriterion("create_id not like", value, "createId");
            return (Criteria) this;
        }

        public Criteria andCreateIdIn(List<String> values) {
            addCriterion("create_id in", values, "createId");
            return (Criteria) this;
        }

        public Criteria andCreateIdNotIn(List<String> values) {
            addCriterion("create_id not in", values, "createId");
            return (Criteria) this;
        }

        public Criteria andCreateIdBetween(String value1, String value2) {
            addCriterion("create_id between", value1, value2, "createId");
            return (Criteria) this;
        }

        public Criteria andCreateIdNotBetween(String value1, String value2) {
            addCriterion("create_id not between", value1, value2, "createId");
            return (Criteria) this;
        }

        public Criteria andModifyTimeIsNull() {
            addCriterion("modify_time is null");
            return (Criteria) this;
        }

        public Criteria andModifyTimeIsNotNull() {
            addCriterion("modify_time is not null");
            return (Criteria) this;
        }

        public Criteria andModifyTimeEqualTo(Date value) {
            addCriterion("modify_time =", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeNotEqualTo(Date value) {
            addCriterion("modify_time <>", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeGreaterThan(Date value) {
            addCriterion("modify_time >", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("modify_time >=", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeLessThan(Date value) {
            addCriterion("modify_time <", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeLessThanOrEqualTo(Date value) {
            addCriterion("modify_time <=", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeIn(List<Date> values) {
            addCriterion("modify_time in", values, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeNotIn(List<Date> values) {
            addCriterion("modify_time not in", values, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeBetween(Date value1, Date value2) {
            addCriterion("modify_time between", value1, value2, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeNotBetween(Date value1, Date value2) {
            addCriterion("modify_time not between", value1, value2, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyIdIsNull() {
            addCriterion("modify_id is null");
            return (Criteria) this;
        }

        public Criteria andModifyIdIsNotNull() {
            addCriterion("modify_id is not null");
            return (Criteria) this;
        }

        public Criteria andModifyIdEqualTo(String value) {
            addCriterion("modify_id =", value, "modifyId");
            return (Criteria) this;
        }

        public Criteria andModifyIdNotEqualTo(String value) {
            addCriterion("modify_id <>", value, "modifyId");
            return (Criteria) this;
        }

        public Criteria andModifyIdGreaterThan(String value) {
            addCriterion("modify_id >", value, "modifyId");
            return (Criteria) this;
        }

        public Criteria andModifyIdGreaterThanOrEqualTo(String value) {
            addCriterion("modify_id >=", value, "modifyId");
            return (Criteria) this;
        }

        public Criteria andModifyIdLessThan(String value) {
            addCriterion("modify_id <", value, "modifyId");
            return (Criteria) this;
        }

        public Criteria andModifyIdLessThanOrEqualTo(String value) {
            addCriterion("modify_id <=", value, "modifyId");
            return (Criteria) this;
        }

        public Criteria andModifyIdLike(String value) {
            addCriterion("modify_id like", value, "modifyId");
            return (Criteria) this;
        }

        public Criteria andModifyIdNotLike(String value) {
            addCriterion("modify_id not like", value, "modifyId");
            return (Criteria) this;
        }

        public Criteria andModifyIdIn(List<String> values) {
            addCriterion("modify_id in", values, "modifyId");
            return (Criteria) this;
        }

        public Criteria andModifyIdNotIn(List<String> values) {
            addCriterion("modify_id not in", values, "modifyId");
            return (Criteria) this;
        }

        public Criteria andModifyIdBetween(String value1, String value2) {
            addCriterion("modify_id between", value1, value2, "modifyId");
            return (Criteria) this;
        }

        public Criteria andModifyIdNotBetween(String value1, String value2) {
            addCriterion("modify_id not between", value1, value2, "modifyId");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_bs_pay_info
     *
     * @mbg.generated do_not_delete_during_merge Tue Oct 24 16:25:32 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_bs_pay_info
     *
     * @mbg.generated Tue Oct 24 16:25:32 CST 2017
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}