package com.everwing.coreservice.common.wy.entity.other.pojo;

import java.io.Serializable;
import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table tc_agent_code
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class TcAgentCode implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tc_agent_code.agent_code_id
     *
     * @mbg.generated
     */
    private String agentCodeId;

    /**
     * Database Column Remarks:
     *   坐席号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tc_agent_code.agent_code
     *
     * @mbg.generated
     */
    private String agentCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tc_agent_code.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tc_agent_code
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tc_agent_code.agent_code_id
     *
     * @return the value of tc_agent_code.agent_code_id
     *
     * @mbg.generated
     */
    public String getAgentCodeId() {
        return agentCodeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tc_agent_code.agent_code_id
     *
     * @param agentCodeId the value for tc_agent_code.agent_code_id
     *
     * @mbg.generated
     */
    public void setAgentCodeId(String agentCodeId) {
        this.agentCodeId = agentCodeId == null ? null : agentCodeId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tc_agent_code.agent_code
     *
     * @return the value of tc_agent_code.agent_code
     *
     * @mbg.generated
     */
    public String getAgentCode() {
        return agentCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tc_agent_code.agent_code
     *
     * @param agentCode the value for tc_agent_code.agent_code
     *
     * @mbg.generated
     */
    public void setAgentCode(String agentCode) {
        this.agentCode = agentCode == null ? null : agentCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tc_agent_code.create_time
     *
     * @return the value of tc_agent_code.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tc_agent_code.create_time
     *
     * @param createTime the value for tc_agent_code.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tc_agent_code
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", agentCodeId=").append(agentCodeId);
        sb.append(", agentCode=").append(agentCode);
        sb.append(", createTime=").append(createTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}