package com.everwing.coreservice.common.wy.entity.other.pojo;

import java.io.Serializable;
import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table tc_agent_code_and_sys_user
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class TcAgentCodeAndSysUser implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tc_agent_code_and_sys_user.id
     *
     * @mbg.generated
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tc_agent_code_and_sys_user.agent_code_id
     *
     * @mbg.generated
     */
    private String agentCodeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tc_agent_code_and_sys_user.sys_user_id
     *
     * @mbg.generated
     */
    private String sysUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tc_agent_code_and_sys_user.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tc_agent_code_and_sys_user
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tc_agent_code_and_sys_user.id
     *
     * @return the value of tc_agent_code_and_sys_user.id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tc_agent_code_and_sys_user.id
     *
     * @param id the value for tc_agent_code_and_sys_user.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tc_agent_code_and_sys_user.agent_code_id
     *
     * @return the value of tc_agent_code_and_sys_user.agent_code_id
     *
     * @mbg.generated
     */
    public String getAgentCodeId() {
        return agentCodeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tc_agent_code_and_sys_user.agent_code_id
     *
     * @param agentCodeId the value for tc_agent_code_and_sys_user.agent_code_id
     *
     * @mbg.generated
     */
    public void setAgentCodeId(String agentCodeId) {
        this.agentCodeId = agentCodeId == null ? null : agentCodeId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tc_agent_code_and_sys_user.sys_user_id
     *
     * @return the value of tc_agent_code_and_sys_user.sys_user_id
     *
     * @mbg.generated
     */
    public String getSysUserId() {
        return sysUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tc_agent_code_and_sys_user.sys_user_id
     *
     * @param sysUserId the value for tc_agent_code_and_sys_user.sys_user_id
     *
     * @mbg.generated
     */
    public void setSysUserId(String sysUserId) {
        this.sysUserId = sysUserId == null ? null : sysUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tc_agent_code_and_sys_user.create_time
     *
     * @return the value of tc_agent_code_and_sys_user.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tc_agent_code_and_sys_user.create_time
     *
     * @param createTime the value for tc_agent_code_and_sys_user.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tc_agent_code_and_sys_user
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", agentCodeId=").append(agentCodeId);
        sb.append(", sysUserId=").append(sysUserId);
        sb.append(", createTime=").append(createTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}